### ISSUE TITLE
App Talk for Nextcloud v20.0.0 on Android cannot load history chat 

### ISSUE THREAD

**Issue by zvwhome** [nextcloud/talk-android#4227] opened 2024-09-17 03:01 UTC
### Steps to reproduce

1. I download app talk from Google playstore
2. I install to my android phone mobile Vivo V30 under Funtouch OS laterst version
3. I setup my nextcloud account
4. App show Join a conversation or start a new one (But This is wrong. It should actually load the chat page)
5. I go to chat history, It show blank page

![223893](https://github.com/user-attachments/assets/328e4314-e062-4363-8f5a-0523e0f23d41)

![223891](https://github.com/user-attachments/assets/06f8cb20-79e8-4e70-8194-70c8934921be)

### Expected behaviour

When we open app after setup account  It should actually load the chat history and show other user

### Actual behaviour

It happen after update v 20.0.0, I will never update anymore

### Device brand and model

Vivo V30

### Android version

14

### Nextcloud Talk app version

20.0.0

### Nextcloud server version

 25.0.3

### Talk version

15.0.8

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by alexhjelmnf** [comment] 2024-09-17 06:56
Same here. New android version is broken
iPhone version works fine in 20.0.0 but not Android.

Its not possible to make new conversations but you can get notifications and you can answer them on the small popup.

**Comment by migulen** [comment] 2024-09-17 07:20
I had the same problem. I closed it yesterday because I upgraded the servers. 

https://github.com/nextcloud/talk-android/issues/4198

I thought that it was "EoS".

**Comment by wolfshade1** [comment] 2024-09-17 09:04
Same thing with my users and my mobile.
Since 15th September. No changes at the server.
Android-Version: 13
Modell: Motorola moto g72

Even upgrading the server and apps it doesn't work. Deleting Account on mobile and fresh installed app bring up the same issue.
Greetings
Kai

**Comment by migulen** [comment] 2024-09-17 11:29
@wolfshade1  See. https://github.com/nextcloud/talk-android/pull/4223

I incorrectly closed my report of the bug, because I arranged "my problem" upgrading to v28.0.10. Sorry.

**Comment by mahibi** [comment] 2024-09-17 12:50
i will close this as duplicate of https://github.com/nextcloud/talk-android/issues/4222

Version 20.0.1 with the fix is released in playstore. If something is still not working, please comment at https://github.com/nextcloud/talk-android/issues/4222

**Closed by mahibi** 2024-09-17 12:50 UTC
Labels: bug, 0. Needs triage
