### ISSUE TITLE
Displayed message repeatedly

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#717] opened 2020-01-27 09:24 UTC
Steps:

1. Open conversation.
2. Scroll through the long conversation list repeatedly to older messages.
3. Write and send the message.
4. **Displaying the same sent message repeatedly.**

The new message is displayed repeatedly. After leaving the conversation and opening it is again displayed correctly.

App:
Android 6
Talk Android 8.0.1

**Comment by markus2330** [comment] 2020-01-27 10:33
I am not sure if this is the same bug, but we had here also messages displaying multiple times. I thought it is related to bad internet connection but it could also be caused by scrolling.

**Comment by mario** [comment] 2020-02-03 10:07
Duplicate of https://github.com/nextcloud/talk-android/issues/684

**Closed by mario** 2020-02-03 10:07 UTC
Labels: bug
