### ISSUE TITLE
App keeps crashed on startup

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2531] opened 2022-10-27 17:52 UTC
### Steps to reproduce

Opened the app app keeps crashing

### Expected behaviour

Should not crash. This happen a few days ago and i cleared the cache and data off the app and it started to work again. 

I collacted some adb phone logs ping me via IM so i can send them to you. 

### Actual behaviour

https://user-images.githubusercontent.com/59488153/198362491-04d5a673-b29d-4eb3-b1e8-57959ea59261.mp4

### Device brand and model

SM-G996U1 

### Android version

12

### Nextcloud Talk app version

15.0.1

### Nextcloud server version

24.0.6

### Talk version

14.0.5

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment] 2022-11-14 09:11
hi @andyxheli thanks for logging the crash :+1:  can you send it it marcel dot hibbe at nextcloud dot com ?

**Comment by timkrueger** [comment] 2022-11-14 10:17
> hi @andyxheli thanks for logging the crash +1 can you send it it marcel dot hibbe at nextcloud dot com ?

He sent it already to me. I forward it.

**Comment by migulen** [comment] 2022-11-21 23:54
@mahibi , @timkrueger 

I've this type of crashing with v15.0.1 and I think it's related to the "disappearing accounts", because they happens doing the same operations that with the related bug. It could happen 1 or 2 times a day.

Clearing cache and data of the nextcloud-talk app and reconfiguring the accounts, it start to work another time. Some crash report logs:

java.lang.NullPointerException
	at com.nextcloud.talk.controllers.ConversationsListController.loadUserAvatar(ConversationsListController.kt:259)
	at com.nextcloud.talk.controllers.ConversationsListController.onCreateOptionsMenu(ConversationsListController.kt:377)
	at com.bluelinelabs.conductor.Controller.createOptionsMenu(Controller.java:1387)
	at com.bluelinelabs.conductor.Router.onCreateOptionsMenu(Router.java:684)
	at com.bluelinelabs.conductor.internal.LifecycleHandler.onCreateOptionsMenu(LifecycleHandler.java:266)
	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2655)
	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3147)
	at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:348)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4143)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3105)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:785)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7560)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by mahibi** [comment] 2022-11-23 11:02
> I've this type of crashing with v15.0.1 and I think it's related to the "disappearing accounts", because they happens doing the same operations that with the related bug. It could happen 1 or 2 times a day.

- [ ] check if it's related to https://github.com/nextcloud/talk-android/issues/2446

**Comment by mahibi** [comment] 2022-12-13 13:28
i can confirm now it's related to https://github.com/nextcloud/talk-android/issues/2446 
thanks for the hint @migulen 
i having a closer look now!

**Comment by migulen** [comment] 2022-12-13 21:12
It's been a pleasure. I'm sure that the hidding and crashing problem is something really "annoying" for users like me, with 2 (or more) accounts.

I'll keep watching for news. 

Nice work.

**Comment by mahibi** [comment] 2022-12-14 15:03
@andyxheli should be fixed with https://github.com/nextcloud/talk-android/pull/2581
if you want, please test this apk: https://github.com/nextcloud/talk-android/pull/2581#issuecomment-1351570524

**Closed** 2022-12-15 12:58 UTC
Labels: bug, 1. to develop
