### ISSUE TITLE
Cannot paste into the join via link field

### ISSUE THREAD

**Issue by JGjorgji** [nextcloud/talk-android#138] opened 2018-04-15 10:13 UTC
If i get a link i can't paste it into the application.

**Comment by JGjorgji** [comment] 2018-04-16 21:10
Phone is Huawei P9 lite with Android 7.
App version: 1.1.1
Also reproducible on i think either Lineage 14.1 or 15.1.

When you tap and hold in the "Conversation link" field expecting paste to appear as in other input fields nothing happens.

**Comment by jookk** [comment] 2018-04-17 05:34
Confirmed on Lineage 14.1.

**Comment by Art4** [comment] 2018-04-27 09:16
Confirmed on Android 5.0.1

**Comment by mario** [comment] 2018-04-28 07:10
@AndyScherzinger wanna investigate?

**Comment by AndyScherzinger** [comment] 2018-04-28 07:51
Sure, also can't paste, same for the server address login field. My guess it is a general issue with the used Ui element.

**Comment by mario** [comment] 2018-04-28 07:56
Fix the element :P

**Comment by xf-** [comment] 2018-04-30 09:29
Tested on Moto Z Android 8 and Pixel 2 Android 8.1 and same issue

**Comment by AndyScherzinger** [comment] 2018-04-30 09:42
Works nowhere since it isn't supported by the used UI library: https://github.com/HITGIF/TextFieldBoxes/issues/76 opened by Mario, let hope it'll be added.

**Comment by mario** [comment] 2018-05-03 15:46
Fix will be in the next release.

**Closed** 2018-05-03 15:46 UTC

**Comment by AndyScherzinger** [comment] 2018-05-03 19:05
@mario also needs to be fixed address login field ;)

**Comment by mario** [comment] 2018-05-03 19:08
Done @AndyScherzinger
