### ISSUE TITLE
Accept text

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#577] opened 2019-07-10 08:57 UTC
I have a nice website I want to share, so I click on share and want to select Talk and then one (or multiple) conversations.

Currently I would have to copy text manually and go into Talk app.

**Comment by mario** [comment] 2019-07-14 13:40
Closing as duplicate of https://github.com/nextcloud/talk-android/issues/308.

**Closed by mario** 2019-07-14 13:40 UTC
Labels: enhancement
