### ISSUE TITLE
Switching between Wifi and Mobile network

### ISSUE THREAD

**Issue by alirasol** [nextcloud/talk-android#653] opened 2019-09-30 10:23 UTC
The call stops when switching from Wifi to 4G network and vice versa. One caller has to end the call and join again to get it working again.

**Comment by jookk** [comment] 2019-10-01 18:53
I think, handover? is not possible.
Your network is changed (ip)

**Comment by alirasol** [comment] 2019-10-01 19:12
I am no developer or expert, but all other services that I use are working when switching between networks. It says "reconnecting" and voilà.

**Comment by mario** [comment] 2019-10-11 18:46
This should work actually. I'll take a look.

**Comment by mario** [comment] 2019-12-27 10:06
Duplicate of https://github.com/nextcloud/talk-android/issues/135

**Closed by mario** 2019-12-27 10:06 UTC
