### ISSUE TITLE
No incoming video in call

### ISSUE THREAD

**Issue by Byter3** [nextcloud/talk-android#3173] opened 2023-07-08 22:54 UTC
### Steps to reproduce

Try to have a video chat

### Expected behaviour

Have incoming video from the other participant

### Actual behaviour

No incoming video in call

### Device brand and model

Samsung Galaxy S21 Ultra

### Android version

13

### Nextcloud Talk app version

17.0.1

### Nextcloud server version

27.0.0

### Talk version

17.0.1

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment] 2023-07-10 07:32
Thanks for reporting @Byter3 
closing as duplicate of https://github.com/nextcloud/talk-android/issues/2704

**Closed by mahibi** 2023-07-10 07:32 UTC
Labels: bug, 0. Needs triage
