### ISSUE TITLE
History doesn't appear to be cached.

### ISSUE THREAD

**Issue by mackenzie-1k4** [nextcloud/talk-android#780] opened 2020-04-06 22:59 UTC
On v8.0.8, when switching between conversations, or switching back to the app after a while, the entire conversation history scrolls by. This has been happening since the last release.

**Comment by mario** [comment] 2020-04-07 05:20
I'm not sure I understand? It shouldn't fetch the whole history (just a part of it), but we indeed don't cache anything in v8.0.8.

**Comment by mackenzie-1k4** [comment] 2020-04-07 09:52
To clarify, when I switch between conversations, or switch back to the app after a while, quite a bit of conversation history scrolls by, which takes around 10-15 seconds. Previously, with older versions, the most recent history seemed to be immediately displayed.

**Comment by mario** [comment] 2020-04-07 09:57
I can't reproduce, but since I'm rewriting this part let's assume it'll be fixed with 9.0 :)

**Comment by mackenzie-1k4** [comment] 2020-04-07 21:13
Great! :-) Keep up the good work.

**Closed** 2020-04-08 03:22 UTC
