### ISSUE TITLE
Does not run in the background and consumes a lot of battery

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/talk-android#3318] opened 2023-09-15 11:45 UTC
### Steps to reproduce

1. Make a call (deactivate the app
2. Try to leave the app (minimize/or try to disable the screen) to go to other apps in paralell
3. talk disconnects

### Expected behaviour

Call will go on when running in the background.

### Actual behaviour

disconnects and call does not proceed.

### Device brand and model

Note10+, Nothing Phon 1, S23 Ultra

### Android version

13,14

### Nextcloud Talk app version

17.0.2

### Nextcloud server version

27.0.2

### Talk version

17.0.3

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment] 2023-09-26 10:26
closing as duplicate of https://github.com/nextcloud/talk-android/issues/2042

**Closed by mahibi** 2023-09-26 10:26 UTC
Labels: bug, 0. Needs triage
