### ISSUE TITLE
Push notifications are not displayed

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/talk-android#1921] opened 2022-04-16 21:03 UTC
## Steps to reproduce
1. Person 1 writes a message to person 2
2. Person 2 does not receive a push notification via the Talk App but via the notifications from the Nextcloud App.

### Expected behaviour
That a push notification is displayed.

### Actual behaviour
Nextcloud Talk Push Notifications are not displayed

## Device information

**Device:** Fairphone2/…
Realme

**Android version:** 10/…
12

**Talk version:** 11.0.0
13.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
23.0.3

**Talk version:** (see apps admin page: `/index.php/settings/apps`)
13.0.5

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
Yes

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

### Server log (data/nextcloud.log)
nothing of interest

```
Insert your server log here
```
nothing of interest

**Comment by mahibi** [comment] 2022-09-12 07:07
closing as duplicate of https://github.com/nextcloud/talk-android/issues/1840

**Closed by mahibi** 2022-09-12 07:07 UTC
Labels: bug, 0. Needs triage
