### ISSUE TITLE
Chat messages are shown up twice

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/talk-android#952] opened 2021-01-05 11:52 UTC
When I send a message to my handy **_in standby-mode_** (no display on) I notice an incoming message by sound. Then when I open chat history the received messages are shown twice (or three times). From now on (after opening the chat app) the further incoming messages are shown in the right way (the old one still shown twice or three times !)
(seems app need to have focus...?)

similiar to #935 

regards , Joe

**Comment by mahibi** [comment] 2021-09-16 10:24
closing this because it seems to be a duplicate of https://github.com/nextcloud/talk-android/issues/935
we probably identified the problem (--> https://github.com/nextcloud/talk-android/issues/1582) so a solution will hopefully be available soon

**Closed by mahibi** 2021-09-16 10:24 UTC
Labels: bug, feature: 🗨️ chat

**Comment by andyxheli** [comment] 2021-09-30 14:16
@mahibi Looks like on v12.2.1 no more duplicate messages. #935 has been closed out.
