### ISSUE TITLE
Not able to execute audio messages with Talk Android 17.1.0

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/talk-android#3325] opened 2023-09-19 12:55 UTC
### Steps to reproduce

Execute audio message

### Expected behaviour

The audio message is played

### Actual behaviour

The audio message is not played

### Device brand and model

Huawei P8 Lite 2017

### Android version

8

### Nextcloud Talk app version

17.1.0

### Nextcloud server version

c.nc.com

### Talk version

c.nc.com

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

None

### Additional information

It works with Talk Android 17.0.2

**Comment by XueSheng-GIT** [comment] 2023-09-23 04:02
I also got feedback by a couple of persons who are not able to play audio messages anymore with talk-android 17.1.0. They press the play button and the loading spinner turns forever.

One person told me he's on android 9.

If additional info is required, I can ask the persons affected.

**Comment by mahibi** [comment] 2023-09-27 08:48
@rapterjet2004 spontaneously any idea if anything changed which might cause this?

**Comment by mahibi** [comment] 2023-09-27 09:15
for now reported for android 8, 9 and 10

**Comment by rapterjet2004** [comment] 2023-09-27 15:37
> @rapterjet2004 spontaneously any idea if anything changed which might cause this?

My first thought was when a voice message is being processed to become a waveform, but there is a time limit of 5 seconds before the process is terminated and the file plays as a regular seekbar. Those versions are pretty old though, perhaps another SDK related issue?

**Comment by ni-tro** [comment] 2023-09-28 05:09
I know of two people with a Samsung phone where it doesn't work since the last update. The recording shows up in their file repository and everything works as expected on their iPad.

**Comment by mahibi** [comment] 2023-09-28 08:54
> I know of two people with a Samsung phone where it doesn't work since the last update. The recording shows up in their file repository and everything works as expected on their iPad.

Do you now which android version they have on the Samsung devices?

**Comment by TBI-NS** [comment] 2023-09-28 09:02
Likewise for our users on most Android versions.

**Comment by ni-tro** [comment] 2023-09-28 11:46
> > I know of two people with a Samsung phone where it doesn't work since the last update. The recording shows up in their file repository and everything works as expected on their iPad.
> 
> Do you now which android version they have on the Samsung devices?

First person: Samsung S7
- Android version 8.0.0
- Samsung Experience 9.0
- Kernel 3.18.91-19497840-QB54396082 dpi@SWDH4606 #1 Tue Jul 26 15:29:15 KST 2022
- Build R16NW.G930FXXU8EVG3
- SE for Android Status: Enforcing SEPF_SM-G930F_8.0.0_0018
- Android Security Patch: 1. September 2020

Second person: Samsung Galaxy A41
- One UI 4.1
- Android 12
- Google Play Systemupdate 1. August 2023
- Kernel: 4.14.186-1568577^
- Build SP1A.210812.016.A415FXXU3DWD2
- SE for Android Status: Enforcing SEPF_SM-A415F_12_0001
- Android Security Patch 1. April 2023

**Comment by Mer0me** [comment] 2023-10-06 08:23
Talk 17.1.0
e/os/ 1.15 Android 12 on Fairphone 3+

My daughter sends a lots of audio messages in a row in the family conversation since a couple of weeks (don't know how it used to work before that, no experience). It seems that the first two audio messages can be played with no problem. The third one loads forever. Killing Talk and relaunch it, I can play the next 2 audio messages, then, the third load forever etc...

![image](https://github.com/nextcloud/talk-android/assets/6248852/8fea8379-707f-43fc-8308-b8225675fcb3)


No problem on the web app, I've just played all this very same audio messages in a row :
![image](https://github.com/nextcloud/talk-android/assets/6248852/ae804c66-d234-4de5-938a-601fe451b50c)

**Comment by mahibi** [comment] 2023-10-12 13:55
i was now able to reproduce this with a Galaxy A32 5G, but i guess it's just depending on TIME_LIMIT which phone will handle it successfully or not.

The problem happens in `AudioUtils`.
Always when "time limit exceeded" is logged it fails. So `result` is empty and
```
while (result.size <= 0) {
	continue
}
```
results in an endless loop (which is also not interrupted when navigating away, so might lead to memory problems).

- Setting TIME_LIMIT = 50000 instead 5000
worked for my case.


Also i somehow had the feeling `onOutputBufferAvailable` was not called reliable (but i might be wrong here) which would also explain this endless loop.

I won't find time for this today. Can you maybe have a closer look @rapterjet2004 ?


Stacktrace:

```
2023-10-11 17:30:19.756 19343-19343 ViewRootIm...tActivity] com.nextcloud.talk2                  I  ViewPostIme pointer 0
2023-10-11 17:30:19.757 19343-19343 GestureDetector         com.nextcloud.talk2                  I  obtain mCurrentDownEvent. id: 517041765 caller: androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent:484 androidx.core.view.GestureDetectorCompat.onTouchEvent:548 androidx.recyclerview.widget.ItemTouchHelper$2.onInterceptTouchEvent:320 
2023-10-11 17:30:19.820 19343-19343 ViewRootIm...tActivity] com.nextcloud.talk2                  I  ViewPostIme pointer 1
2023-10-11 17:30:19.820 19343-19343 GestureDetector         com.nextcloud.talk2                  I  obtain mCurrentMotionEventRaw. action: 1 id: 469486108
2023-10-11 17:30:19.836 19343-19445 NuMediaExtractor        com.nextcloud.talk2                  V  NuMediaExtractor constructor
2023-10-11 17:30:19.840 19343-19445 NuMediaExtractor        com.nextcloud.talk2                  V  track of type 'audio/raw' does not publish bitrate
2023-10-11 17:30:19.841 19343-19445 NuMediaExtractor        com.nextcloud.talk2                  V  NuMediaExtractor destructor
2023-10-11 17:30:19.842   877-877   audit                   auditd                               E  type=1327 audit(1697038219.836:2164): proctitle="com.nextcloud.talk2"
2023-10-11 17:30:19.842 19343-19414 libc                    com.nextcloud.talk2                  W  Access denied finding property "sys.perf.boostopt"
2023-10-11 17:30:19.859 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/x-ima
2023-10-11 17:30:19.860 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/mpeg-L1
2023-10-11 17:30:19.861 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/mpeg-L2
2023-10-11 17:30:19.862 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime video/mp43
2023-10-11 17:30:19.863 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime video/wvc1
2023-10-11 17:30:19.864 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime video/x-ms-wmv
2023-10-11 17:30:19.865 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/x-ms-wma
2023-10-11 17:30:19.866 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime video/x-ms-wmv7
2023-10-11 17:30:19.868 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime video/x-ms-wmv8
2023-10-11 17:30:19.871 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/x-adpcm-dvi-ima
2023-10-11 17:30:19.872 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/x-adpcm-dvi-ima
2023-10-11 17:30:19.873 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/x-adpcm-ms
2023-10-11 17:30:19.873 19343-19445 AudioCapabilities       com.nextcloud.talk2                  W  Unsupported mime audio/x-adpcm-ms
2023-10-11 17:30:19.898 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unrecognized profile/level 32768/256 for video/mp4v-es
2023-10-11 17:30:19.905 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime video/avc-wfd
2023-10-11 17:30:19.911 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime image/vnd.android.heic
2023-10-11 17:30:19.912 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime image/vnd.android.heic
2023-10-11 17:30:19.913 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime image/vnd.android.heic
2023-10-11 17:30:19.914 19343-19445 VideoCapabilities       com.nextcloud.talk2                  W  Unsupported mime image/vnd.android.heic
2023-10-11 17:30:19.921 19343-19343 RealImageLoader         com.nextcloud.talk2                  I  🧠 Successful (MEMORY_CACHE) - https://sermo.nextcloud.com/index.php/avatar/marcel/512
2023-10-11 17:30:19.935 19343-19343 RealImageLoader         com.nextcloud.talk2                  I  🧠 Successful (MEMORY_CACHE) - https://sermo.nextcloud.com/index.php/avatar/marcel/512
2023-10-11 17:30:19.965 19343-19481 CCodec                  com.nextcloud.talk2                  I  state->set(ALLOCATING)
2023-10-11 17:30:19.965 19343-19481 CCodec                  com.nextcloud.talk2                  I  allocate(c2.android.raw.decoder)
2023-10-11 17:30:19.968 19343-19481 Codec2Client            com.nextcloud.talk2                  I  Available Codec2 services: "default" "default0" "software"
2023-10-11 17:30:19.970 19343-19481 CCodec                  com.nextcloud.talk2                  I  setting up 'default' as default (vendor) store
2023-10-11 17:30:19.983 19343-19481 CCodec                  com.nextcloud.talk2                  I  Created component [c2.android.raw.decoder]
2023-10-11 17:30:19.983 19343-19481 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(ALLOCATED)
2023-10-11 17:30:19.984 19343-19481 CCodecConfig            com.nextcloud.talk2                  D  read media type: audio/raw
2023-10-11 17:30:19.985 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: algo.buffers.max-count.values
2023-10-11 17:30:19.986 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: output.subscribed-indices.values
2023-10-11 17:30:19.986 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: input.buffers.allocator-ids.values
2023-10-11 17:30:19.986 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: output.buffers.allocator-ids.values
2023-10-11 17:30:19.986 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: algo.buffers.allocator-ids.values
2023-10-11 17:30:19.986 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: output.buffers.pool-ids.values
2023-10-11 17:30:19.987 19343-19481 ReflectedParamUpdater   com.nextcloud.talk2                  D  extent() != 1 for single value type: algo.buffers.pool-ids.values
2023-10-11 17:30:19.988 19343-19481 CCodecConfig            com.nextcloud.talk2                  I  query failed after returning 8 values (BAD_INDEX)
2023-10-11 17:30:19.988 19343-19481 CCodecConfig            com.nextcloud.talk2                  D  c2 config diff is Dict {
                                                                                                      c2::u32 coded.bitrate.value = 64000
                                                                                                      c2::u32 input.buffers.max-size.value = 65536
                                                                                                      c2::u32 input.delay.value = 0
                                                                                                      string input.media-type.value = "audio/raw"
                                                                                                      string output.media-type.value = "audio/raw"
                                                                                                      c2::u32 raw.channel-count.value = 2
                                                                                                      c2::u32 raw.pcm-encoding.value = 0
                                                                                                      c2::u32 raw.sample-rate.value = 44100
                                                                                                    }
2023-10-11 17:30:19.989 19343-19481 MediaCodec              com.nextcloud.talk2                  I  MediaCodec will operate in async mode
2023-10-11 17:30:19.989 19343-19481 MediaCodec              com.nextcloud.talk2                  D  flushMediametrics
2023-10-11 17:30:19.990 19343-19481 CCodec                  com.nextcloud.talk2                  D  [c2.android.raw.decoder] buffers are bound to CCodec for this session
2023-10-11 17:30:19.990 19343-19481 CCodec                  com.nextcloud.talk2                  I  appPid(19343) width(0) height(0)
2023-10-11 17:30:19.990 19343-19481 CCodecConfig            com.nextcloud.talk2                  D  no c2 equivalents for track-id
2023-10-11 17:30:19.990 19343-19481 CCodecConfig            com.nextcloud.talk2                  D  no c2 equivalents for durationUs
2023-10-11 17:30:19.990 19343-19481 CCodecConfig            com.nextcloud.talk2                  D  no c2 equivalents for bits-per-sample
2023-10-11 17:30:19.990 19343-19481 CCodecConfig            com.nextcloud.talk2                  D  no c2 equivalents for flags
2023-10-11 17:30:19.990 19343-19481 Codec2Client            com.nextcloud.talk2                  W  query -- param skipped: index = 1107298332.
2023-10-11 17:30:19.990 19343-19481 CCodec                  com.nextcloud.talk2                  D  encoding statistics level = 0
2023-10-11 17:30:19.990 19343-19481 CCodec                  com.nextcloud.talk2                  D  setup formats input: AMessage(what = 0x00000000) = {
                                                                                                      int32_t android._codec-pcm-encoding = 2
                                                                                                      int32_t bitrate = 64000
                                                                                                      int32_t channel-count = 2
                                                                                                      int32_t max-input-size = 65536
                                                                                                      string mime = "audio/raw"
                                                                                                      int32_t pcm-encoding = 2
                                                                                                      int32_t sample-rate = 44100
                                                                                                      int64_t durationUs = 15211972
                                                                                                    }
2023-10-11 17:30:19.990 19343-19481 CCodec                  com.nextcloud.talk2                  D  setup formats output: AMessage(what = 0x00000000) = {
                                                                                                      int32_t android._codec-pcm-encoding = 2
                                                                                                      int32_t channel-count = 2
                                                                                                      string mime = "audio/raw"
                                                                                                      int32_t pcm-encoding = 2
                                                                                                      int32_t sample-rate = 44100
                                                                                                      int32_t channel-mask = 0
                                                                                                      int32_t android._config-pcm-encoding = 2
                                                                                                    }
2023-10-11 17:30:19.991 19343-19481 CCodecConfig            com.nextcloud.talk2                  I  query failed after returning 8 values (BAD_INDEX)
2023-10-11 17:30:19.991 19343-19445 MediaCodec              com.nextcloud.talk2                  D  keep callback message for reclaim
2023-10-11 17:30:19.992 19343-19481 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(STARTING)
2023-10-11 17:30:19.993 19343-19481 Codec2Client            com.nextcloud.talk2                  W  query -- param skipped: index = 1342179345.
2023-10-11 17:30:19.993 19343-19481 Codec2Client            com.nextcloud.talk2                  W  query -- param skipped: index = 2415921170.
2023-10-11 17:30:19.993 19343-19481 C2Store                 com.nextcloud.talk2                  D  Using ION
2023-10-11 17:30:19.994 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  D  [c2.android.raw.decoder#551] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
2023-10-11 17:30:19.995 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  I  [c2.android.raw.decoder#551] Created output block pool with allocatorID 16 => poolID 27 - OK
2023-10-11 17:30:19.996 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  D  [c2.android.raw.decoder#551] Configured output block pool ids 27 => OK
2023-10-11 17:30:19.996 19343-19481 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(RUNNING)
2023-10-11 17:30:19.999 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  I  [c2.android.raw.decoder#551] 4 initial input buffers available
2023-10-11 17:30:20.001 19343-19343 NuMediaExtractor        com.nextcloud.talk2                  V  NuMediaExtractor constructor
2023-10-11 17:30:20.004 19343-19343 NuMediaExtractor        com.nextcloud.talk2                  V  track of type 'audio/raw' does not publish bitrate
2023-10-11 17:30:20.005 19343-19343 NuMediaExtractor        com.nextcloud.talk2                  V  selectTrack, track[0]: audio/raw
2023-10-11 17:30:20.158 19343-19343 GestureDetector         com.nextcloud.talk2                  I  handleMessage TAP
2023-10-11 17:30:24.874 19343-19481 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(STOPPING)
2023-10-11 17:30:24.874 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  D  [c2.android.raw.decoder#551] MediaCodec discarded an unknown buffer
2023-10-11 17:30:24.874 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  D  [c2.android.raw.decoder#551] MediaCodec discarded an unknown buffer
2023-10-11 17:30:24.874 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  D  [c2.android.raw.decoder#551] MediaCodec discarded an unknown buffer
2023-10-11 17:30:24.874 19343-19481 CCodecBufferChannel     com.nextcloud.talk2                  D  [c2.android.raw.decoder#551] MediaCodec discarded an unknown buffer
2023-10-11 17:30:24.875 19343-19481 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(ALLOCATED)
2023-10-11 17:30:24.875 19343-19481 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(RELEASING)
2023-10-11 17:30:24.876 19343-19488 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] release(1)
2023-10-11 17:30:24.876 19343-19343 NuMediaExtractor        com.nextcloud.talk2                  V  NuMediaExtractor destructor
2023-10-11 17:30:24.877 19343-19488 CCodec                  com.nextcloud.talk2                  I  [c2.android.raw.decoder] state->set(RELEASED)
2023-10-11 17:30:24.877 19343-19481 hw-BpHwBinder           com.nextcloud.talk2                  I  onLastStrongRef automatically unlinking death recipients
2023-10-11 17:30:24.877 19343-19343 AudioUtils              com.nextcloud.talk2                  D  time limit exceeded
2023-10-11 17:30:24.877 19343-19481 MediaCodec              com.nextcloud.talk2                  I  Codec shutdown complete
2023-10-11 17:30:24.877 19343-19481 MediaCodec              com.nextcloud.talk2                  D  flushMediametrics
2023-10-11 17:30:24.878 19343-19481 MediaCodec              com.nextcloud.talk2                  D  flushMediametrics
2023-10-11 17:30:25.027 19343-19356 nextcloud.talk2         com.nextcloud.talk2                  I  Background concurrent copying GC freed 94589(10MB) AllocSpace objects, 13(316KB) LOS objects, 43% free, 30MB/54MB, paused 414us,54us total 269.708ms
2023-10-11 17:30:25.029 19343-19357 InputTransport          com.nextcloud.talk2                  D  Input channel destroyed: 'ClientS', fd=190
```

**Comment by TBI-NS** [comment] 2023-10-26 09:24
Even with the latest beta version installed on my Huawei P30 Pro, I still can't play voice messages. Please, we need a patch very quickly because you have broken an essential feature for any business.

Everything was working perfectly before.
I don't understand how you can close this ticket without waiting for real user feedback. This is not the first time I've seen this in NextCloud development.

**Comment by siriwliw98** [comment] 2023-12-12 19:30
Bonjour,

J'aimerais vous signaler que ce problème persiste encore même sur la dernière version de l'application ! Avez-vous prévu une correctifs à ce problème ?

Merci d'avance.

**Comment by TBI-NS** [comment] 2023-12-12 19:38
> Bonjour,
> 
> 
> 
> J'aimerais vous signaler que ce problème persiste encore même sur la dernière version de l'application ! Avez-vous prévu une correctifs à ce problème ?
> 
> 
> 
> Merci d'avance.

I confirm what he has said; everything was working, and you've broken an essential functionality for the use of the app on Android. Despite numerous reports on GitHub, you continue to add other features instead of debugging a basic functionality that is necessary for proper use. I still can't understand how the development team can overlook such an essential test as the voice message functionality, especially since a fix has already been written, if I'm not mistaken, but we are still waiting for it to be updated on our phones. It is intolerable and incomprehensible to see the Android development team leave such a crucial feature completely bugged. This is putting companies and associations that use Nextcloud every day in an awkward position.

Please issue an emergency patch, this is becoming really embarrassing.

**Comment by AlanRichardin** [comment] 2023-12-13 07:19
Waiting for update ... 3 months guys :/

**Comment by maygauth** [comment] 2023-12-13 08:25
I'm confused because I see that the tickets are closed without any real solution behind, this functionality worked before. There are several of us who are in the same delicate position and we see that new features are coming but that the essential features are not repaired. Please do what is necessary as quickly as possible.

**Comment by mahibi** [comment] 2023-12-13 10:05
Please provide information for smartphone model, Android OS version and NC talk app version.

**Comment by siriwliw98** [comment] 2023-12-13 10:37
Hi @mahibi,

Thanks for your reply.
For me its a Samsung note 9 (Android 10), and I'm using the last stable version of NC talk (18.0.0)

**Comment by TBI-NS** [comment] 2023-12-13 11:50
> Please provide information for smartphone model, Android OS version and NC talk app version.

Android 10 / 11 
Samsung 
Huawei 
Honor 

All in last version.

**Comment by AlanRichardin** [comment] 2023-12-13 14:17
Huawei P20 pro
NC last version

**Comment by mahibi** [comment] 2023-12-15 08:32
@siriwliw98 @TBI-NS @AlanRichardin et.al
could you try out the apk from
https://github.com/nextcloud/talk-android/pull/3515#issuecomment-1854568456
and let us know if this fixes the issue for you?

**Comment by siriwliw98** [comment] 2023-12-15 09:08
@mahibi Je confirme que les audios fonctionnent correctement sur cet APK

**Comment by TBI-NS** [comment] 2023-12-15 09:09
> @mahibi Je confirme que les audios fonctionnent correctement sur cet APK


Je confirme également

**Closed** 2023-12-22 15:06 UTC
Labels: bug, 1. to develop
