### ISSUE TITLE
Call ending when switching away or pressing home button.

### ISSUE THREAD

**Issue by Skalli** [nextcloud/talk-android#957] opened 2021-01-16 16:43 UTC
I'm using Nextcloud Talk 8.2.0. When I'm in a call and out the app in the background. The call is ended immediately. As when I press the home button, or switch to another app.
Before it would continue the calls at least for a short while, but now it's over immediately, which is annoying.
I'm on Android 10.

**Comment by AMajor-C** [comment] 2021-11-02 13:53
I hope it will be fixed soon because withouth the feature the call function overall almost useless (for me)

**Comment by mahibi** [comment] 2021-12-14 13:04
With v13 there is picture in picture support that will continue the call when switching away or pressing home button.
However this doesn't help when PIP is not supported by the device, so in the future there should be additionally some service to continue the call, see https://github.com/nextcloud/talk-android/issues/1688

closing as duplicate of https://github.com/nextcloud/talk-android/issues/1688

**Closed by mahibi** 2021-12-14 13:04 UTC
Labels: bug, feature: ☎️ call
