### ISSUE TITLE
Turn Talk into a real messenger

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/talk-android#675] opened 2019-11-24 11:54 UTC
Recently Wire has been sold to an American company and weakened their privacy promise. This could happen to any company owned messenger. I know there are decentralized solutions like Matrix. But as Nextcloud grows and grows and big organizations roll it out to thousands of users, it would be great to make Talk the messenger that doesn't only reach people within your organization. There should be some kind of feature that makes it possible to discover who of my contacts also runs Talk on his or her phone.

**Comment by nickvergessen** [comment] 2019-11-24 13:05
Duplicate of https://github.com/nextcloud/spreed/issues/21

**Closed by nickvergessen** 2019-11-24 13:05 UTC
