### ISSUE TITLE
Background calls

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/talk-android#1614] opened 2021-10-03 17:54 UTC
## Steps to reproduce
1. Join to a call
2. Press "back" or "home" or "power" button
3. Get pissed off with dropped call

### Expected behaviour
When app is in ongoing call then it should have a permanent notification to prevent suspending and killing by android

### Actual behaviour
Rarely  it potst a notification with (!)Android system but it has no effect

## Device information

**Device:** Redmi4X (Santoni)

**Android version:** 7.1.2

**Talk version:** 12.2.1

## Server information

**Nextcloud version:** 22.2.0

**Talk version:**  12.1.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes)

**Custom STUN server configured:** no

**Comment by mahibi** [comment] 2021-10-04 10:43
duplicate of https://github.com/nextcloud/talk-android/issues/957

**Closed by mahibi** 2021-10-04 10:43 UTC
Labels: bug, 0. Needs triage
