### ISSUE TITLE
No notification for new messages! (Android 10)

### ISSUE THREAD

**Issue by Akrobs** [nextcloud/talk-android#870] opened 2020-07-04 09:44 UTC
Hi, Mario!
I have a new phone, Samsung S10e, with Android 10. Im testing Talk v8.0.9 and 9.0.5b. Both version have no notification. All permissions are set.

**Comment by jakobroehrl** [comment] 2020-07-06 11:58
Did you disable the battery optimization?
-> https://dontkillmyapp.com/?app=Nextcloud%20Talk

**Comment by Akrobs** [comment] 2020-07-11 12:01
> 
> 
> Did you disable the battery optimization?
> -> https://dontkillmyapp.com/?app=Nextcloud%20Talk

Thaks for you reply! Yep, I'm disable all optimization, add Talk app to exclude on sleep, but nothing...

**Comment by guzzisti** [comment] 2020-07-11 12:12
duplicate of #866

**Comment by Akrobs** [comment] 2020-07-11 15:15
Yep, but on Samsung A6 Android 10, it works very well!

**Comment by Akrobs** [comment] 2020-10-02 21:26
It works on 8.0.10!!!!! Thanks!

**Closed** 2020-10-06 09:52 UTC
