### ISSUE TITLE
Background Calls

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/talk-android#2498] opened 2022-10-14 10:37 UTC
It would be nice if it would be possible to minimize the app and the call will still proceed, like in skype, teams,...
Morover picture in picture on video calls would be fine as well

**Comment by timkrueger** [comment] 2022-10-17 10:48
Thanks for your suggestions @MrLoverLoverMMMM. There exists issues for both points.

Duplicate of: #1688, #2042

**Closed by timkrueger** 2022-10-17 10:48 UTC
Labels: enhancement, 0. Needs triage
