### ISSUE TITLE
Talk 14.1.0: Sporadically: Last (or lasts) message dissapear after doing a reply to messages before the last one.

### ISSUE THREAD

**Issue by migulen** [nextcloud/talk-android#2298] opened 2022-08-13 14:28 UTC
### Steps to reproduce

Not always happens, i don't catch the correct way to reproduce. I've seen this issue in Talk-Android v14.1.0 (and think in Talk-Android v14.0.2 but not sure). I'm trying v14.1.1-RC1 and haven't seen it for now.

1. open a conversation
2. write and send 4 (or  more) messages
3. in a 1-to-1 chat, the other person must send a message (or more)
4. do a reply to some of the prior messages

### Expected behaviour

1. to 4. The same.

5. After you do a "reply" all the previous messages must be shown plus the replied message and his text.

### Actual behaviour

1. to 4. The same.

5. the messages after the original one replied "dissapear" and the replied message and his text appear instead.

### Device brand and model

Xiaomi Mi 9

### Android version

10

### Nextcloud Talk app version

14.1.0

### Nextcloud server version

23.0.7

### Talk version

13.0.7

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by timkrueger** [comment] 2022-08-15 08:21
Duplicate of #2290

**Closed by timkrueger** 2022-08-15 08:21 UTC
Labels: bug, 0. Needs triage

**Comment by migulen** [comment] 2022-10-13 23:50
@timkrueger, I seems v15.0.0-RC4 mitigated a lot  this situation.
