### ISSUE TITLE
Can't answer calls or text from 2nd account

### ISSUE THREAD

**Issue by Minnietheandroid** [nextcloud/talk-android#1117] opened 2021-04-10 00:10 UTC
Hi Devs.
I'm wondering if anyone else has this problem...

When I sign in on multiple accounts, I can't answer calls or text received on the 'other' account.

So if I'm on Account A, I can't answer calls or message for Account B and vice versa..
It rings and notifies ok but the interface is missing the usual phone/video answer buttons and shows only the red hang-up option.

Just thought I'd ask as the IOS automatically switches between them on incoming call and seems to function as expected.
 
Thanks for all your hard work on this great app.

**Comment by jakobroehrl** [comment] 2021-04-12 08:10
Is this the same?
https://github.com/nextcloud/talk-android/issues/862

**Comment by mahibi** [comment] 2021-04-12 08:32
what version of the app did you use @Minnietheandroid ?

**Comment by Minnietheandroid** [comment] 2021-04-12 11:42
Thank you for the replies.
 @jakobroehrl - Yes that's it, stuck with no option but to hang up. I'm sorry I didn't see that earlier.

@mahibi - I first saw it on the current Google Play stable release, so signed up for the beta channel and it happens there too.
My current version is 11.2.0 RC1

**Comment by jakobroehrl** [comment] 2021-04-12 12:20
@mahibi 
Let's close this in favour of https://github.com/nextcloud/talk-android/issues/862 ?

**Comment by mahibi** [comment] 2021-04-12 12:42
duplicate of #862

**Closed** 2021-04-12 12:42 UTC
Labels: bug
