### ISSUE TITLE
Not ringing when calling

### ISSUE THREAD

**Issue by Byter3** [nextcloud/talk-android#1910] opened 2022-04-09 18:18 UTC
Not ringing when calling

Basically on all android device I managed Samsung/Xiaomi etc...

Talk set to as an axeption to to all power managment feature on all devices.

NC 21.0.7
 All up-to-date devices with up-to-date Talks

**Comment by mahibi** [comment] 2022-04-09 21:44
close as duplicate of https://github.com/nextcloud/talk-android/issues/1840

**Closed by mahibi** 2022-04-09 21:44 UTC
Labels: bug, 0. Needs triage
