### ISSUE TITLE
I want to share upload feature or send file directly

### ISSUE THREAD

**Issue by ririx2** [nextcloud/talk-android#587] opened 2019-07-31 12:13 UTC
I have inovation about this, i use some library, like Nextcloud:Android-library, Filepicker and Flipboard.

I work with some friend to finishing this feature.
how i can to contribute about this?

#sorry if my English too bad

**Comment by mario** [comment] 2020-03-24 11:55
Hi, sorry that I never responded here, it somehow slipped. While the app changed significantly, the code might still be useful - where did you hide it? :)

**Comment by nickvergessen** [comment] 2020-06-12 12:57
Duplicate of #435

**Closed by nickvergessen** 2020-06-12 12:57 UTC
