### ISSUE TITLE
Support push notifications for systems without Google Play Services

### ISSUE THREAD

**Issue by nathan-sain** [nextcloud/talk-android#75] opened 2018-01-20 05:31 UTC
Would it be possible to add support for push notifications using services other than F/GCM which requires Google Play Services?

For example, [Pushy](https://pushy.me) works on platforms which do not have Google Play Services installed. The [Fastmail Android app uses Pushy](https://blog.fastmail.com/2016/12/21/what-we-talk-about-when-we-talk-about-push/) on systems without support for F/GCM. 

Although Pushy is a commercial service it is based upon [MQTT](https://mqtt.org), which is an open standard. There  are open source libraries, servers, and clients available for MQTT which could allow Nextcloud administrators to run their own push notification message broker.

**Comment by mario** [comment] 2018-01-20 06:21
There is already a discussion here about this: https://github.com/nextcloud/talk-android/issues/58

As for the actual push infrastructure - sure, you could NOT rely on Google, but you'd also need to do changes to Nextcloud and the way it does push. Keep it mind very minimal amount of data is sent via push message, and it's all encrypted anyway.

I'll close this issue as there's already so much said about it in the issue mentioned above.

**Closed by mario** 2018-01-20 06:21 UTC

**Comment by nathan-sain** [comment] 2018-01-20 06:41
That make sense. We can keep the discussion on #58. I did want to note that the Google Play Service isn't just a push notification service. It provides a large number of other services for the android platform that many of us are not comfortable with installing, regardless of the security of the F/GCM messages. For that reason IMHO it's worth having an alternative push option.

**Comment by mario** [comment] 2018-01-20 06:43
@nathan-sain I completely understand. For now, you can install MicroG which allows you to use push while NOT having Google services installed.

**Comment by Joeviocoe** [comment] 2019-07-08 18:20
Just to be clear, MicroG cannot just be "installed".  It requires a custom ROM and possibly rooting\unlocked bootloader.

It's like trying to close one door, and another opens.

**Comment by f4grx** [comment] 2019-10-18 14:29
microg works in lineage os, yes, either by patching or by using a ROM that already supports microg.

But the issue is not the privacy of data, which is ensured.

The issue is the reliance on google servers.

**Comment by 05nelsonm** [comment] 2019-11-14 21:33
https://github.com/guardianproject/orbot/issues/282
