### ISSUE TITLE
Talk 14.1.0: Sporadically: Written message only showes up after rejoining the conversation

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#2290] opened 2022-08-11 15:33 UTC
## Steps to reproduce
1. write a message
2. message is sometimes not shown up
3. go to the conversion overwiew
4. Open conversation again
5. message is there

**Comment by timkrueger** [comment] 2022-08-12 08:09
I can't reproduce this issue. How often happened this to you?

Can you please also provide some details about your device, android version and Nextcloud server/spreed version?

**Comment by migulen** [comment] 2022-08-13 13:48
The same issue happens to me. It usually happens when connection isn't good enought.

Nextcloud Server: v23.0.7
Nextcloud Talk-Android: v14.1.0 
Nextcloud Spreed: v13.0.7

but i've seen with prior versions of client and server.

Could be that happens because my Nextcloud instance is working after a proxy.

HTTP Server: Apache 2.4.38-3+deb10u7, working behind a Apache 2.4.38-3+deb10u7 acting like proxy.

Now i've good mobile  connection, but seems that Nextcloud Talk v14.1.1-RC1 reduce this issue.

I hope this info helps.

**Comment by andyxheli** [comment] 2022-08-13 20:54
Same issue here not all the time but more of the time running  

- SM-G996U1 
- Android 12 Android  

- NC App 14.1.1 RC1 
- NC Server 24.0.4 
- NC Server Talk App 14.0.4

**Comment by timkrueger** [comment] 2022-08-15 09:42
I tested it again with 14.1.0 and was able to reproduce it. It's really sporadically. With 14.1.1-RC1 it was not possible to reproduce it. 

In 14.1.1-RC1 we fixed multiple NPEs which can somehow related to this. I'll close this issue as fixed and add it to the 14.1.1 milestone. Whenever this happen again please feel free to report it.

**Closed by timkrueger** 2022-08-15 09:42 UTC
Labels: bug, approved

**Comment by fuzunspm** [comment] 2023-03-20 18:23
I have same issue on talk 16.0 latest version

**Comment by jakobroehrl** [comment] 2023-03-21 06:06
Please do not go back, wait a little bit, I think the messages will pop up. 
Sometimes the loading in background could take some time

**Comment by migulen** [comment] 2023-03-21 22:25
@jakobroehrl , I'm not 100% sure,  but I think it happened one time to me today with v16.0.0. 

5 minutes passed and the message didn't pop up.

I will report if it happens another time.
