### ISSUE TITLE
NO talk notification

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/talk-android#868] opened 2020-06-22 17:07 UTC
### Steps to reproduce
1. Write message in Nextcloud talk app
2. press send
3. 

### Expected behaviour
- Tell us what should happen
Notification on android receiver phone

### Actual behaviour
- Tell us what happens
nothing

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment] 2020-06-23 05:59
Moved to android-talk repo

**Comment by stefan-niedermann** [comment] 2020-06-23 06:13
Well with this little information it will be pretty hard to find any cause.

You said that the *receiver* didn't get any notification.

- Do you get notifications for messages send by this person?
- Does *no* receiver of your messages get notifications?
- Which version exactly are you using and which is your receiver?
- Which version is the Nextcloud instance and the Talk server app?
- Are there any logs on your Nextcloud server?
- Do you both have installed Google Play Services?
- Does it happen all the time or just a few times?
- ...

**Comment by MarcS1975** [comment] 2020-06-23 11:52
On Tue, Jun 23, 2020 at 7:13 AM Niedermann IT-Dienstleistungen <
notifications@github.com> wrote:

> Well with this little information it will be pretty hard to find any cause.
>
> You said that the *receiver* didn't get any notification.
>
>    - Do you get notifications for messages send by this person?
>
> no. Noone on our server (only 2 users) gets notifications (Chrome, Android
app and iPhone app)

**Comment by Ivansss** [comment] 2020-06-23 12:01
Hi @MarcS1975,
Do you have the notifications app installed in your Nextcloud?

**Comment by MarcS1975** [comment] 2020-06-23 12:03
yes version 2.7.0

**Comment by nickvergessen** [comment] 2020-06-23 13:58
Duplicate of https://github.com/nextcloud/notifications/issues/668

**Closed by nickvergessen** 2020-06-23 13:58 UTC
