### ISSUE TITLE
Share Filename Conflicts

### ISSUE THREAD

**Issue by isaiah-v** [nextcloud/talk-android#2109] opened 2022-06-01 02:57 UTC
## Steps to reproduce
1. Download "[Dream](https://play.google.com/store/apps/details?id=com.womboai.wombodream&gl=US)"
2. Generate an image.
3. Click share within the Dream app
4. Choose to share with the Nextcloud Talk app
5. Share the image with someone

Make 2 or more images and share them both using the steps above.

### Behavior
Following the steps above, the first image is always shared. No matter how many images I generate, only the first image generated is shared. That image is shared over and over.

### Expected behavior
The image I select to share should be the image shared. And all other images generated should persist.

### Notes
It looks like the issue might be with how the file is saved in nextcloud. The image name is always "Untitled.jpg". Subsequent image generations don't save to the nextcloud file system.  I'm thinking it fails to save, and it ends up sharing the existing file with the same name. Personally, I don't care if shared images have a UUID name or something random. But the share should always work and it shouldn't overwrite existing files.

Side Note: I've noticed similar issues when images are shared with me using a filename that already exists in my Talk file directory.

**Comment by timkrueger** [comment] 2022-08-12 08:17
I close this as duplicate of #2280, because the other issue has the more general description.

**Comment by timkrueger** [comment] 2022-08-12 08:20
Duplicate of #2280

I close this, because the other issue has the more general description.

**Comment by timkrueger** [comment] 2022-08-12 08:20
Duplicate of #2280

I close this, because the other issue has the more general description.

**Closed by timkrueger** 2022-08-12 08:20 UTC
Labels: bug, 0. Needs triage
