### ISSUE TITLE
Adapt text colour in conversion overview after changing theme

### ISSUE THREAD

**Issue by philodi** [nextcloud/talk-android#1103] opened 2021-04-06 16:12 UTC
After changing from bright theme to dark theme and closing adjustments text clolour is still dark before the dark gray background.
-> low contrast
Textclolour does not become bright bevor restarting nextcloud talk.

Operating system: LineageOS 15.1
Talk version: 11.1.2 from F-Droid (120000005)

**Comment by mahibi** [comment] 2021-04-07 06:46
Duplicate of #915

**Closed** 2021-04-07 06:46 UTC
