### ISSUE TITLE
App crashes while joining call on 15.0 RC3

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2445] opened 2022-09-29 21:08 UTC
### Steps to reproduce

Click to join call 
Rings 
Crashes

### Expected behaviour

Should work

### Actual behaviour

Not working 

https://user-images.githubusercontent.com/59488153/193141907-1b0e13c5-9367-49ee-b682-e0db9d052941.mp4

### Device brand and model

SM-G996U1 

### Android version

12

### Nextcloud Talk app version

15.0 RC3

### Nextcloud server version

24.0.5

### Talk version

Lastes version 

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by timkrueger** [comment] 2022-09-30 10:12
I tried to reproduce this without success. 

Is it possible to get a test access to your instance?

And with 'Talk version: Latest version' you mean 14.0.5?

**Comment by andyxheli** [comment] 2022-09-30 12:03
Hey @timkrueger yes I can share out the test link so we can do some testing? Let me know and good email to send the link too? I should be available in about an hour or so will that work ?

**Comment by andyxheli** [comment] 2022-09-30 17:25
I also just sent feedback when thr app crashed maybe that will help you I referenced this issue under details

**Comment by migulen** [comment] 2022-10-03 19:34
Hi @andyxheli and @timkrueger, same happening to me since v15.0.0-RC2.  (v15.0.0-RC1, and priors, works ok)

**Device brand and model**

Xiaomi Mi 9

**Android version**

12

**Nextcloud Talk app version**

15.0.0-RC2 and 15.0.0-RC3.  

**Nextcloud server version**

23.0.8

**Talk version**

13.0.8

**Custom Signaling server configured**

No response

**Custom TURN server configured**

Yes

**Custom STUN server configured**

Yes

**Android logs**

No response

**Server log**

No response

**Additional information**

No response

**Comment by andyxheli** [comment] 2022-10-03 19:44
Thanks @migulen Yes, @timkrueger i can confirm i downgrade to RC 1 and its working with no issues. While on RC 2 & RC 3 the the app crashes but i noticed that on other side it shows me like I'm connected but then it goes away file 30 to 60 sec but on the android crash and when i look at my status it show be in a meeting but I'm not since the app crashed like you seen in the above video. Maybe this will help :)

**Comment by timkrueger** [comment] 2022-10-05 09:35
> Let me know and good email to send the link too? 

Sorry. I was off work the last days. Would be great if you can send me a test account to tim(dot)krueger(at)nextcloud(dot)com

And thank you @migulen  and @andyxheli  figuring out that it looks like the problem was introduced with RC2. I'll work on it.

**Comment by andyxheli** [comment] 2022-10-05 13:09
Hi @timkrueger no worries at all. Thank you for your reply. I'll send you an email with a link in about am hour I'm on my way to the office.

**Comment by andyxheli** [comment] 2022-10-05 14:07
@timkrueger I sent you a username and password to my nextcloud server via email.

**Comment by timkrueger** [comment] 2022-10-06 12:28
I was able to reproduce the problem on the instance from @andyxheli. Thank you very much for your support.

In logcat I found that exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.nextcloud.talk.models.json.participants.Participant$ActorType com.nextcloud.talk.models.json.participants.Participant.getCalculatedActorType()' on a null object reference
	at com.nextcloud.talk.activities.CallActivity.setupVideoStreamForLayout(CallActivity.java:2364)
	at com.nextcloud.talk.activities.CallActivity.lambda$processUsersInRoom$14$com-nextcloud-talk-activities-CallActivity(CallActivity.java:1904)
	at com.nextcloud.talk.activities.CallActivity$$ExternalSyntheticLambda20.run(Unknown Source:4)
	at android.app.Activity.runOnUiThread(Activity.java:7133)
	at com.nextcloud.talk.activities.CallActivity.processUsersInRoom(CallActivity.java:1903)
	at com.nextcloud.talk.activities.CallActivity.receivedSignalingMessage(CallActivity.java:1650)
	at com.nextcloud.talk.activities.CallActivity.receivedSignalingMessages(CallActivity.java:1634)
	at com.nextcloud.talk.activities.CallActivity.access$2300(CallActivity.java:185)
	at com.nextcloud.talk.activities.CallActivity$13$1.onNext(CallActivity.java:1494)
	at com.nextcloud.talk.activities.CallActivity$13$1.onNext(CallActivity.java:1484)
	at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onNext(ObservableRetryPredicate.java:69)
	at io.reactivex.internal.operators.observable.ObservableTakeWhile$TakeWhileObserver.onNext(ObservableTakeWhile.java:88)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:107)
	at io.reactivex.internal.operators.observable.ObservableRepeatWhen$RepeatWhenObserver.onNext(ObservableRepeatWhen.java:100)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

It looks like that this problem is fixed in Talk 15.

**Comment by migulen** [comment] 2022-10-10 18:07
> I was able to reproduce the problem on the instance from @andyxheli. Thank you very much for your support.
> 
> In logcat I found that exception:
> 
> ```java
> java.lang.NullPointerException: Attempt to invoke virtual method 'com.nextcloud.talk.models.json.participants.Participant$ActorType com.nextcloud.talk.models.json.participants.Participant.getCalculatedActorType()' on a null object reference
> 	at com.nextcloud.talk.activities.CallActivity.setupVideoStreamForLayout(CallActivity.java:2364)
> 	at com.nextcloud.talk.activities.CallActivity.lambda$processUsersInRoom$14$com-nextcloud-talk-activities-CallActivity(CallActivity.java:1904)
> 	at com.nextcloud.talk.activities.CallActivity$$ExternalSyntheticLambda20.run(Unknown Source:4)
> 	at android.app.Activity.runOnUiThread(Activity.java:7133)
> 	at com.nextcloud.talk.activities.CallActivity.processUsersInRoom(CallActivity.java:1903)
> 	at com.nextcloud.talk.activities.CallActivity.receivedSignalingMessage(CallActivity.java:1650)
> 	at com.nextcloud.talk.activities.CallActivity.receivedSignalingMessages(CallActivity.java:1634)
> 	at com.nextcloud.talk.activities.CallActivity.access$2300(CallActivity.java:185)
> 	at com.nextcloud.talk.activities.CallActivity$13$1.onNext(CallActivity.java:1494)
> 	at com.nextcloud.talk.activities.CallActivity$13$1.onNext(CallActivity.java:1484)
> 	at io.reactivex.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onNext(ObservableRetryPredicate.java:69)
> 	at io.reactivex.internal.operators.observable.ObservableTakeWhile$TakeWhileObserver.onNext(ObservableTakeWhile.java:88)
> 	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:107)
> 	at io.reactivex.internal.operators.observable.ObservableRepeatWhen$RepeatWhenObserver.onNext(ObservableRepeatWhen.java:100)
> 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
> 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
> 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> ```
> 
> It looks like that this problem is fixed in Talk 15.

@timkrueger Nice, but it will be fixed on android nextcloud-talk v15.0.0 milestone, or v15.1.0 ?

**Closed** 2022-10-11 06:44 UTC
Labels: bug, 1. to develop

**Comment by timkrueger** [comment] 2022-10-11 10:16
It's fixed in 15.0.0 RC4. It should be available beta testers in the PlayStore in a few hours or you can download it from the [releases page](https://github.com/nextcloud/talk-android/releases/tag/v15.0.0rc4).

**Comment by andyxheli** [comment] 2022-10-11 16:25
@timkrueger Now the session joins but after a bit the remote users video turns off you can still hear them if they leave and rejoin the video comes back. So while i was on the call on Android Talk i joined it via web and i seen multiple sessions of myself as soon as i joined via web the Android Talk crashed and then it kicked me out of the web i had to rejoin and it was still displaying multiple session after 30 secs or so it cleared all the other sessions

**Comment by migulen** [comment] 2022-10-12 15:03
> @timkrueger Now the session joins but after a bit the remote users video turns off you can still hear them if they leave and rejoin the video comes back. So while i was on the call on Android Talk i joined it via web and i seen multiple sessions of myself as soon as i joined via web the Android Talk crashed and then it kicked me out of the web i had to rejoin and it was still displaying multiple session after 30 secs or so it cleared all the other sessions

@timkrueger I can confirm every word from @andyxheli . I've tested between clients:

Case 1:
   v14.2.0 <> v15.0.0-RC4    (being both of them initial callers or receivers of the call): In this case only the user with client v15.0.0-RC4 lost the video from sended by the v14.2.0 client after few seconds. The v14.2.0 client see perfectly the video send by the v15.0.0-RC4 all the time.
   
Case 2:
   v15.0.0-RC4 <> v15.0.0-RC4 (being both of them initial callers or receivers of the call): In this case both sides could lost video signal after few seconds, and it's possible that it don't start receiving video signal at all. Sometimes the caller don't lost the video signal... but the receiver of the call (for me test) always lost the video signal.
   
   The voice works perfectly on both cases.

**Comment by andyxheli** [comment] 2022-10-12 15:10
@migulen Thank you for confirming :) I created a new ticket on this also 

https://github.com/nextcloud/talk-android/issues/2486
