### ISSUE TITLE
 No message notifications from Talk app on Android 10 / 11

### ISSUE THREAD

**Issue by bobreidx** [nextcloud/talk-android#896] opened 2020-09-18 22:58 UTC
Pixel 3a, Android 10, build QQ3A.200805.001 and Android 11, build RP1A.200720.009
Talk app v 8.0.9, installed via Play Store
All battery suggestions followed and notification settings checked for proper setup and config.

**Comment by meonkeys** [comment] 2020-09-23 16:40
Looks like a dup of #866

**Comment by Akrobs** [comment] 2020-10-03 09:12
In last 8.0.10 wjrk on S10e, Android 10. Try it!

**Comment by bobreidx** [comment] 2020-10-05 14:55
I tried the 8.0.10 update, and there was no change.

**Comment by bobreidx** [comment] 2020-10-05 15:03
UPDATE: I discovered with the help of a friend, was that the Talk desktop settings for notifications are overriding the Android app notification settings. To wit, once I toggled the desktop settings to allow all notifications, the Android app notifications began to work normally. This, despite the fact that the Android app was already set to allow all notifications.

I'm not sure if this has been previously documented (apologies if so), but my Android app notifications appear to be working now.

Although maybe a bit too well, as the app has a setting for assigning a sound, and Android also has a setting for assigning a sound to an app. So now, I am getting TWO notification sounds playing upon receiving a Talk message.

**Comment by theoneandonly-vector** [comment] 2020-10-07 08:29
It's not due to Android 10. I have 4 different devices, where notifications are working and all of them run Android 10.

**Comment by axheli** [comment] 2020-11-02 14:59
yup same issue on androis 9\10\11

**Comment by Skalli** [comment] 2021-01-16 13:30
I'm also on Android 10 and don't receive notifications for text messages. My conversation partner gets the notifications (I think Android 10).
It's very annoying since it's easy to miss messages. Is there any information that I can provide to help fix the issue?
@bobreidx: You said that you changed it in the desktop settings? What and where? I have only the Nextcloud Desktop Client on Linux, but no option to change any settings that deal with talk notifications.

**Comment by nickvergessen** [comment] 2021-05-19 12:01
Closing as duplicate of #866

**Closed by nickvergessen** 2021-05-19 12:01 UTC
Labels: bug
