### ISSUE TITLE
Mute calls in app doesn't appear to do anything.

### ISSUE THREAD

**Issue by Luticus** [nextcloud/talk-android#1183] opened 2021-04-28 05:28 UTC
## Steps to reproduce
1. join conversation
2. select mute calls in android app
3. have someone start a call, watch call go though anyway 

### Expected behaviour
Tell us what should happen
when i select mute call, calls for that conversation should not "ring" my phone

### Actual behaviour
Tell us what happens instead
Calls ring my phone regardless of the mute calls toggle, they simply ignore it it seems. Unless i'm misunderstanding the purpose of that toggle.

## Device information

**Device:** Fairphone2/…
samsung note 10+

**Android version:** 10/…
11

**Talk version:** 11.0.0
11.1.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)
21.0.1
**Talk version:** (see apps admin page: `/index.php/settings/apps`)
11.1.2
**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)
yes - coturn
**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)
yes - coturn

**Comment by mahibi** [comment] 2021-04-28 08:36
thanks @Luticus , this should not happen. 
similar problems are reported here: https://github.com/nextcloud/talk-android/issues/892

**Comment by nickvergessen** [comment] 2021-05-19 13:04
Closing as duplicate of #892

**Closed by nickvergessen** 2021-05-19 13:04 UTC
Labels: bug
