### ISSUE TITLE
ScreenSharing Android to Android or Desktop

### ISSUE THREAD

**Issue by csoc49** [nextcloud/talk-android#2788] opened 2023-02-21 11:04 UTC
It should be possible to share your screen, like on desktop devices.
Currently, only the split desktop screen can be displayed.
Feature: ScreenShare Android to Android or desktop

**Comment by mahibi** [comment] 2023-02-21 12:06
closing as duplicate of https://github.com/nextcloud/talk-android/issues/1530

**Closed by mahibi** 2023-02-21 12:06 UTC
Labels: enhancement, 0. Needs triage
