### ISSUE TITLE
Nextcloud Talk Mobile Application 

### ISSUE THREAD

**Issue by Gowtham-eng** [nextcloud/talk-android#2150] opened 2022-06-13 07:02 UTC
Dear Team,

Whenever I open the Nextcloud Talk Mobile Application from Android takes too much time to buffer the chats.

It's like frustrating to use the nextcloud talk application on mobile. I have tried these buffering issues from both testing servers of Nextcloud which is in the domain of demo1.nextcloud.com & my on-prem server it has similar problems with loading the chat in talk.

1) Are there any ways to optimize the buffering load of Nextcloud Talk?

![1655102951172](https://user-images.githubusercontent.com/69081075/173297809-cc537acb-c17f-4bb3-8102-bf3797858691.jpg)

**Comment by mahibi** [comment] 2022-06-16 07:46
hi @Gowtham-eng 
these issues are well known.
One main issue is that there is no offline mode right now which would make the app more responsive.
If the mobile internet connection is slow it can indeed be a bit annoying to wait for the app to show the conversations.
So if the conversations load in the end but it's "only" slow, than it's unfortunately the expected behaviour right now.

Because offline mode requires a lot of remodeling this might still take a while, but it is oune of our main goals and we are constantly working into this direction.

i will close this issue as duplicate of https://github.com/nextcloud/talk-android/issues/217

**Closed by mahibi** 2022-06-16 07:46 UTC
Labels: enhancement, 0. Needs triage
