### ISSUE TITLE
ask for permission before the first call/on the 1st app start?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#820] opened 2020-05-07 05:51 UTC
it would be better to ask for permission before the first call otherwise the phone is ringing while the user is trying to change the permissions...

**Comment by mario** [comment] 2020-05-07 19:00
I agree.

**Comment by nickvergessen** [comment] 2020-06-12 14:15
Duplicate of #380

**Closed by nickvergessen** 2020-06-12 14:15 UTC
Labels: enhancement
