### ISSUE TITLE
(UI) Change call buttons to allow Video calling and speaker

### ISSUE THREAD

**Issue by EthanHindmarsh** [nextcloud/talk-android#1666] opened 2021-11-04 05:54 UTC
**Is your feature request related to a problem? Please describe.**
1. Start a call on non-video mode
2. Notice the four buttons - Message, speaker, mute, end call
3. End call
4. Start a call on video mode
5. Notice the four buttons - Message, video, mute, end call

You are not able to put a video call on speaker; You are not able to turn your camera on during a normal call without rejoining.

**Describe the solution you'd like**
Just make the video button the fifth button, make the UI consistent regardless of how you start the call
It is definitely annoying to have to reconnect to a call just to enable my camera
Thanks 👍

**Comment by mahibi** [comment] 2021-11-04 09:47
this is on our list and will be implemented in the future!
closing because it's a duplicate of https://github.com/nextcloud/talk-android/issues/708

**Closed by mahibi** 2021-11-04 09:47 UTC
Labels: enhancement, 0. Needs triage
