### ISSUE TITLE
Settimg for muting the ring sound when calling

### ISSUE THREAD

**Issue by StyXman** [nextcloud/talk-android#723] opened 2020-02-09 22:36 UTC
It's 23.30, my kids are sleeping, I'm trying to test video calls between two users, and even when I disabled all notifications and all volume settings are in 0 (granted, 'only' according to the volume app in f-droid), I get a loud sound when calling someone else.

**Comment by mario** [comment] 2020-02-11 10:24
Thanks for your request. Let me think about this.

**Comment by nickvergessen** [comment] 2020-02-11 10:51
Hu? Any calling app plays a ringing for you while you start a call?

**Comment by nickvergessen** [comment] 2020-02-11 10:55
Okay, for outgoing video calls the sound is played via the speaker by default. that's of course a bit disturbing but also the same as all others handle it.

**Comment by nickvergessen** [comment] 2020-06-12 14:04
Duplicate of #772 which has more info

**Closed by nickvergessen** 2020-06-12 14:04 UTC
Labels: enhancement
