### ISSUE TITLE
Talk links should open in the app and not in the browser

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#3635] opened 2024-02-07 11:00 UTC
**Is your feature request related to a problem? Please describe.**

It happens regularly that colleagues post links in a chat to another room, e.g. to join a call. If I click on the link, the browser opens the link

**Describe the solution you'd like**

The app should open the corresponding room directly in the app

**Comment by mahibi** [comment] 2024-02-12 09:59
closing as duplicate of https://github.com/nextcloud/talk-android/issues/847
will have a closer look when time allows

**Closed by mahibi** 2024-02-12 09:59 UTC
Labels: enhancement, 0. Needs triage
