### ISSUE TITLE
Notifications over UnifiedPush (F-Droid-Version) 

### ISSUE THREAD

**Issue by SymplyTheBest** [nextcloud/talk-android#3773] opened 2024-03-28 10:24 UTC
The title says it all.

Nextcloud provides a UnifiedPush server app. Why not facilitate notifications in Talk app over nextcloud server?

**Comment by mahibi** [comment] 2024-04-04 12:04
duplicate of https://github.com/nextcloud/talk-android/issues/257

**Closed by mahibi** 2024-04-04 12:04 UTC
Labels: enhancement, 0. Needs triage, feature: 🔔 notifications
