### ISSUE TITLE
Notifications are on /loud even if phone is muted/vibration

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/talk-android#238] opened 2018-07-16 10:59 UTC
On my Phone, once I set up the notification, it is ringing even it the normal android notification is muted or on vibration

Android 8.0
Talk-Version Beta 5

**Comment by mario** [comment] 2018-07-16 12:03
Currently expected behaviour. I'll work on it eventually to respect system sound settings.

**Comment by jancborchardt** [comment] 2018-07-16 15:18
Marking as high because not honoring this is at best annoying and at worst quite embarassing in meetings or the cinema etc.

**Comment by mario** [comment] 2018-07-16 20:24
I agree @jancborchardt and @Bolli84 - so this will be in the next big stable release.

**Closed** 2018-08-03 07:40 UTC
Labels: enhancement, high
