### ISSUE TITLE
Is necessary add feature for capability adding attachments to chats directly from mobile devices

### ISSUE THREAD

**Issue by neerro** [nextcloud/talk-android#946] opened 2020-12-11 11:18 UTC
At present time (the issue regarding Nextcloud Talk Android version 8.1.0) users have no any ability to attach to any kind of chats any files directly from storage of their mobile devices (it's possible only from cloud storage without any additional options). So please add to another releases that feature for ability using Android Nextcloud Talk app to the full extend.

**Comment by tigermick** [comment] 2020-12-15 17:57
Hi,
Thank you for this great app but this feature is very important for me too.
I hope it will be possible as quick as possible.

**Comment by Chartman123** [comment] 2020-12-18 20:49
Duplicate of #435

**Comment by neerro** [comment] 2020-12-21 09:07
> 
> 
> Duplicate of #435

It seems that NC developers are not straight-thinking. Because is feature are most important for many peoples in according to the best practice of another same apps.

**Closed** 2021-01-30 22:40 UTC
Labels: enhancement
