### ISSUE TITLE
Reply refinements

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#703] opened 2020-01-14 11:55 UTC
### Posting
> ![Screenshot_2020-01-14-12-51-16-822_com nextcloud talk2](https://user-images.githubusercontent.com/213943/72342510-e0be0800-36cc-11ea-8a4f-797dfd70f979.jpg)

### Quote
> ![Screenshot_2020-01-14-12-51-27-216_com nextcloud talk2](https://user-images.githubusercontent.com/213943/72342511-e1569e80-36cc-11ea-9443-c1958d23174b.jpg)

For now the timestamp and the avatar should be removed from the quote and the quote preview.
Especially the timestamp is very confusing, as it might be from a different day.

**Comment by mario** [comment] 2020-01-14 12:08
Duplicate of https://github.com/nextcloud/talk-android/issues/699 - the avatars are removed, but for the next stable version (so 9.0.0). I'll remove the timestamp .

**Closed** 2020-01-14 21:53 UTC
