### ISSUE TITLE
Android app stuck at "Allow access" after login

### ISSUE THREAD

**Issue by madpipeline** [nextcloud/talk-android#678] opened 2019-12-01 21:20 UTC
When I try to login, the app gets stuck on the allow access screen:

![photo_2019-12-01_23-17-37](https://user-images.githubusercontent.com/3527534/69920457-efd85600-1490-11ea-9bea-7eff42799349.jpg)

I don't know what do do from here. I don't know what more information I can provide in this case.

**Comment by mario** [comment] 2019-12-02 08:18
There's a 99,99% chance that this is a server setup issue. Did you look at the logs on your server?

**Comment by ovidiub13** [comment] 2019-12-02 08:42
I tried, they never show up in the logs page. I'll try again, and check the console logs.

**Comment by mario** [comment] 2019-12-09 09:08
@ovidiub13 any update?

**Comment by ovidiub13** [comment] 2019-12-10 07:47
Yes, after pressing the `Grant access` button, I get no logs on the server.

Here are the whole process logs:

Entering the server URL in the app produces this:

```
app_1    | 172.23.0.6 -  10/Dec/2019:07:23:54 +0000 "GET /status.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:23:54 +0000] "GET /status.php HTTP/1.1" 200 151 "-" "Mozilla/5.0 (Android) Nextcloud-Talk v7.0.8" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:23:55 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:23:55 +0000] "GET /index.php/login/flow HTTP/1.1" 200 1799 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:23:55 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:23:55 +0000] "GET /core/js/oc.js?v=d9044872 HTTP/1.1" 200 5618 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:23:55 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:23:55 +0000] "GET /js/core/merged-template-prepend.js?v=d9044872 HTTP/1.1" 200 2960 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:23:55 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:23:55 +0000] "GET /apps/accessibility/js/accessibility?v=0 HTTP/1.1" 200 65 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
```
Pressing the `Log in` button produces this:
<img src="https://user-images.githubusercontent.com/3527534/70505684-4436a200-1b31-11ea-9f12-9fba5c33d0b6.jpg" width="200">

```
app_1    | 172.23.0.6 -  10/Dec/2019:07:24:31 +0000 "GET /index.php" 303
web_1    | 192.168.96.7 - - [10/Dec/2019:07:24:31 +0000] "GET /login/flow/grant?clientIdentifier=&stateToken=1PXzVqNypbGFwZHKSeW46rLxNlzfc7i1Jvfcp0nLDAndouX98WoE60huzEjYhOdT HTTP/1.1" 303 0 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:24:31 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:24:31 +0000] "GET /login?redirect_url=/login/flow/grant%3FclientIdentifier%3D%26stateToken%3D1PXzVqNypbGFwZHKSeW46rLxNlzfc7i1Jvfcp0nLDAndouX98WoE60huzEjYhOdT HTTP/1.1" 200 1572 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:24:31 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:24:31 +0000] "GET /core/js/oc.js?v=d9044872 HTTP/1.1" 200 5618 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
```
After entering the credentials and logging in I get these logs:

```
app_1    | 172.23.0.6 -  10/Dec/2019:07:25:16 +0000 "POST /index.php" 303
web_1    | 192.168.96.7 - - [10/Dec/2019:07:25:17 +0000] "POST /login HTTP/1.1" 303 0 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:25:17 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:25:17 +0000] "GET /login/flow/grant?clientIdentifier=&stateToken=1PXzVqNypbGFwZHKSeW46rLxNlzfc7i1Jvfcp0nLDAndouX98WoE60huzEjYhOdT HTTP/1.1" 200 1640 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:25:17 +0000 "GET /index.php" 200
web_1    | 192.168.96.7 - - [10/Dec/2019:07:25:17 +0000] "GET /core/js/oc.js?v=d9044872 HTTP/1.1" 200 5689 "-" "Oneplus A0001 (Nextcloud Talk)" "79.113.204.37"
```

Now I get the `Grant access` screen. Clicking the `Grant access` button produces no logs.

After about 1-2 minutes I get these logs: 

```
app_1    | 172.23.0.6 -  10/Dec/2019:07:26:18 +0000 "GET /index.php" 204
web_1    | 192.168.96.7 - - [10/Dec/2019:07:26:18 +0000] "GET /index.php/204 HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.9.2" "79.113.204.37"
app_1    | 172.23.0.6 -  10/Dec/2019:07:26:18 +0000 "GET /index.php" 204
web_1    | 192.168.96.7 - - [10/Dec/2019:07:26:18 +0000] "GET /index.php/204 HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.9.2" "79.113.204.37"
```

But I suspect these are from the Nextcloud app, not the Talk app.

**Comment by rosetree** [comment] 2019-12-14 10:39
Thank you for investigating this. I have similar issues on my instance, when logging in with username and password. I didn’t dive deep into the container logs, but Nextcloud Talk appears in the Security settings of my account. Login with the Nextcloud Android App works fine. Please let me know if I can help with this discussion.

@mario, if you see a 99,99% chance of this being a server setup issue, could you please share some information on what you suspect to be the cause of this behavior?

**Comment by mario** [comment] 2019-12-14 10:45
Can one of you please share a test account to mario@nextcloud.com?

**Comment by ovidiub13** [comment] 2019-12-14 12:30
I've made an account for you and sent you a password reset email.

**Comment by mario** [comment] 2019-12-14 21:30
@madpipeline " Network Error " when I try to reset my password.

**Comment by madpipeline** [comment] 2019-12-16 10:55
Yeah.. my brother also reported that on this server... Not sure what's causing it nor how to fix. I'll do some digging and get back to you.

**Comment by madpipeline** [comment] 2019-12-16 11:04
I've fixed the error thanks to https://github.com/nextcloud/server/issues/4352. You can try again now.

**Comment by mario** [comment] 2019-12-16 11:13
Tried it, works like a charm. So I really have to close the issue since I have no way to debug as it seems to be working :(

**Closed by mario** 2019-12-16 11:13 UTC

**Comment by rosetree** [comment] 2019-12-16 11:49
Thanks, both of you! Setting [`overwriteprotocol`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=overwriteprotocol#proxy-configurations) to `https` worked for me as well.

**Comment by mario** [comment] 2019-12-16 11:52
Awesome!

**Comment by madpipeline** [comment] 2019-12-16 11:54
Just tested. So the issue is caused by a wrong link generation on the server if NC is not managing SSL and you have a reverse proxy in front of it. SO it's a server error, but the App should still tell you there is an error, instead of just doing nothing.

**Comment by mario** [comment] 2019-12-16 11:56
The app can't know because there is no error generated on the server :)
