### ISSUE TITLE
Talk for Android uses very much internal memory for user data

### ISSUE THREAD

**Issue by philodi** [nextcloud/talk-android#1099] opened 2021-04-05 13:13 UTC
Hello,

Talk uses 7.4GB of the internal memory of my mobile phone for user data. After deleting user data and authenticating again memory usage increases in a few days again up to several gigabytes.
Operating system: LineageOS 15.1
Talk version: 11.1.2 from F-Droid (120000005)

Same problem happens with an other mobile phone (both phones have talk conversations with each other):
Operating system: Android 7.0
Talk version: 11.1.0 from google play store

3rd mobile phone has the same issues:
Operating system: Android 8.1.0
Talk version: 11.1.0

Where do I find the data on my mobile phone?
How do I prevent nextcloud talk from using so much memory?

**Comment by mahibi** [comment] 2021-04-06 07:35
this sounds like a log is flooded. might be https://github.com/nextcloud/talk-android/issues/1013 which i want to fix soon!
are you aware if wifi/ mobile internet connections were switched off for a while?

**Comment by philodi** [comment] 2021-04-06 07:44
Thank you very much!

Yes, wifi/mobile internet is switched off several hours daily. I might give more information on the memory consuming files when getting a look at the files of the internal memory.

**Comment by mahibi** [comment] 2021-04-06 09:26
I'm closing this issue since it's a duplicate of #1013 
Feel free to comment there..

Unfortunately it seems there is no possibilty to get the log files as non root user at the moment

**Closed by mahibi** 2021-04-06 09:26 UTC
Labels: approved, bug
