### ISSUE TITLE
Screenshare for Andrpid Talk App

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/talk-android#3331] opened 2023-09-21 07:59 UTC
Use case: I replaced my desktop with Samsung DEX and I love it. The only thing I miss is the ability to share screenshots with Talk. The Screenshare plugin is not compatible with Chrome or Firefox for Android and unfortunately not with Samsung Internet.

Is it possible to get this plugin or make the Talk app support Screenshare Out Of The Box like Goto Meeting?

**Comment by mahibi** [comment] 2023-09-26 10:44
you mean you want to share the android screen while being in a call? if yes, it's a duplicate of https://github.com/nextcloud/talk-android/issues/1530

**Comment by MrLoverLoverMMMM** [comment] 2023-09-26 10:47
Yes, it is a duplicate
-------- Ursprüngliche Nachricht --------Von: Marcel Hibbe ***@***.***> Datum: 26.09.23  12:44  (GMT+01:00) An: nextcloud/talk-android ***@***.***> Cc: GVL ***@***.***>, Author ***@***.***> Betreff: Re: [nextcloud/talk-android] Screenshare for Andrpid Talk App (Issue
  #3331) 
you mean you want to share the android screen while being in a call? if yes, it's a duplicate of #1530

**Closed** 2023-09-27 09:19 UTC
Labels: enhancement, 0. Needs triage

**Comment by MrLoverLoverMMMM** [comment] 2023-11-21 10:42
I would really be happy if this feature would not be set to ice.
Goto Webinar, Goto Meeting, Teams,... many more already support screenshare.
I wanna use my phone for presentations in Samsung Dex and with this feature I could replace my presentation pc.
