### ISSUE TITLE
Nextcloud Talk App Android: Attachments aren´t sent

### ISSUE THREAD

**Issue by Rei-DBG** [nextcloud/talk-android#2587] opened 2022-11-21 17:53 UTC
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

open the nextcloud talk app and take a picture to attach to a nextcloud talk chat. Press the blue "send"-Arrow, but this picture will not appear in your chat and never arrives to the members of this chat. Same problem with other attachment types such as pictures from the gallery. 
A nearby problem is that in our pc-Version of nextcloud talk upload is only possible from the nextcloud drive, but not from local pc. Is it possible, that the administrator can block uploads from local devices for the pc online version as well as for app version linked to this special local implementation of nextcloud?

### Expected behaviour

I also contacted nextcloud for getting an advice how to succeed in this procedure, but they told me to give this report on github. Please fix this bug

### Actual behaviour

see above: no reaction

### Android version

12

### Device brand and model

Sony XQ-AS52

### Stock or custom OS?

Stock

### Nextcloud android app version

15.0.1

### Nextcloud server version

now available

### Using a reverse proxy?

I don't know

**Comment by ASerbinski** [comment] 2022-11-21 23:04
If you hit the HQ/LQ button in the camera mode so that it says LQ, does it work then? If so, this is a duplicate of https://github.com/nextcloud/talk-android/issues/2519 which is already fixed and will be included in Talk 15.0.2, the RC of which is scheduled to be released TODAY, so should be available for you within a few days.

**Comment by migulen** [comment] 2022-11-22 00:03
@ASerbinski , take a look at https://github.com/nextcloud/talk-android/pull/2581#issuecomment-1322803929 . I have this problem with QA (https://github.com/nextcloud/talk-android/pull/2581) but not with v15.0.1. I only test trying to attach pictures from the gallery.

**Comment by ASerbinski** [comment] 2022-11-22 01:14
That doesn't matter, the issue is with the size of the file. Below 1 MB works, above does not. Please test as indicated and confirm behavior. 2581 is different altogether.

**Comment by migulen** [comment] 2022-11-22 04:07
@ASerbinski, **I can upload files below 1MB and greater than 1MB (4MB) shared from gallery to nextcloud-talk app, or uploaded directly from nextcloud-talk app. Tested on with v15.0.1**. So, I don't have this problem.

But I can confirm that I have a "strange" problem with 2581 uploading a file below 1MB. That problem has magically has disappeared. Is 2581 so different from v15.0.1 ¿?

 Well, It doesn't matter. I wish it will be resolved in short time.
 
 Goodbye.

**Comment by ASerbinski** [comment] 2022-11-22 04:14
@migulen - whatever issue you are having is not related to this bug.

**Comment by mahibi** [comment] 2022-11-22 12:30
this should be a duplicate of https://github.com/nextcloud/talk-android/issues/2519 so it should be fixed with version 15.0.2 
The release candidate 15.0.2 RC1 will arrive today in playstore (how to become a beta tester: https://github.com/nextcloud/talk-android#testing-test_tube)
You can also already install it from by https://github.com/nextcloud/talk-android/releases/tag/v15.0.2rc1

**Comment by ASerbinski** [comment] 2022-11-24 23:38
Reporter appears to be gone and since it seems to be a duplicate, I'm closing.

**Closed by ASerbinski** 2022-11-24 23:38 UTC
Labels: bug, duplicate
