### ISSUE TITLE
Sharing photos in talk

### ISSUE THREAD

**Issue by WarpinWolf** [nextcloud/talk-android#680] opened 2019-12-07 17:32 UTC
Hi, referring also to #326 - the idea is, that you click on the (+) button and are able to select pictures/attachments from your LOCAL device - maybe in the background uploading to some "special" talk shares folder... Instead of having to upload first, and selecting then....

**Comment by mario** [comment] 2019-12-08 11:34
Duplicate of https://github.com/nextcloud/talk-android/issues/435.

**Closed by mario** 2019-12-08 11:34 UTC
