### ISSUE TITLE
No overview of conversations

### ISSUE THREAD

**Issue by Tino-ko** [nextcloud/talk-android#2124] opened 2022-06-02 12:39 UTC
Hi,
for a few weeks we have been having problems with the Nextcloud Talk app for Android (the IOS app works as usual).

## Steps to reproduce
1. Open the Talk app
2. log in
3. -> Overview of previous chats is missing

### Expected behavior
View an overview of recent chats/messages

### Actual behavior
If the app is opened, an empty window appears, the overview of previous chats is missing (we only see gray bars).
If a new conversation is started and a contact is selected via the app, the older chats are available and telephony and chat functions work without any problems.

For testing, I restored an older backup of 6.5. the Nextcloud and the external signal server, but could not detect any change in behavior. I suspect this is related to the latest update to the Android app.

It is strange that users who are members of the "admin" group are not affected by this issue. Talkgroup restrictions are not specified.
The problem was first reported to me on May 12th or 13th.

## Device information

**Device:** different / Samsung S20

**Android version:** different, up to 12

**Talk Version:** 14.0.1

## Server information

**Nextcloud version: [Nextcloud HanssonIT VM] (23.0.5)

**Talk version: 13.0.6

**Custom signaling server configured: I can't find it at https://domain.tld/settings/admin/talk#signaling_server

**Custom TURN server configured: yes

**Custom STUN server configured: yes

### Server log (data/nextcloud.log)
No entries related to Talk

</details>

**Comment by AlvaroBrey** [comment] 2022-06-02 12:56
Duplicate of #2123

**Closed by AlvaroBrey** 2022-06-02 12:56 UTC
Labels: bug, 0. Needs triage
