### ISSUE TITLE
Uploading Videos and Photos does not work with the current android app and nextcloud 25

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/talk-android#2557] opened 2022-11-10 11:21 UTC
### Steps to reproduce

1.) Install nextcloud 25
2.) Install talk on android (best would be Samsung with Android  )
3.) Try to upload from device a video or photo to the chat
4.) See the failure

### Expected behaviour

Upload of photos and videos work without issues

### Actual behaviour

No upload anymore since update to nc 25

### Device brand and model

Samsung Z Fold 4

### Android version

12

### Nextcloud Talk app version

15.0.1

### Nextcloud server version

25.0.1

### Talk version

15.0.1

### Custom Signaling server configured

No

### Custom TURN server configured

No

### Custom STUN server configured

No

### Android logs

Still no possibility to receive logs at android. Where to find them?

### Server log

```bash
no errors at the server logs.
```

### Additional information

See video

**Comment by MrLoverLoverMMMM** [comment] 2022-11-10 11:25
https://user-images.githubusercontent.com/17781278/201078869-5b768939-03c9-4f7b-82f3-a56f8135b06d.mp4

**Comment by TeslaBenny** [comment] 2022-11-11 16:26
I get the same behavior on NC 24.0.6. Seems to be an issue on the app side of 15.0.1.

### Device brand and model
Samsung Galaxy S20 FE 5G

### Android version
12

### Nextcloud Talk app version
15.0.1

### Nextcloud server version
24.0.6

### Talk version
14.0.6

**Comment by TeslaBenny** [comment] 2022-11-11 16:40
Is this a duplicate of #2519 ?  When is 15.0.2 expected to hit Google Play Store?

**Comment by ASerbinski** [comment] 2022-11-11 22:53
@TeslaBenny : yes, this is a duplicate of that bug.

**Comment by mahibi** [comment] 2022-11-14 09:02
@MrLoverLoverMMMM & @TeslaBenny 
so you can confirm it is fixed when trying this version?: https://github.com/nextcloud/talk-android/pull/2532#issuecomment-1295052027

**Comment by mahibi** [comment] 2022-11-14 09:45
@MrLoverLoverMMMM confirmed it's solved (duplicate of https://github.com/nextcloud/talk-android/issues/2519)

15.0.2 might be released this week.

**Closed by mahibi** 2022-11-14 09:45 UTC
Labels: bug, duplicate
