### ISSUE TITLE
Fairphone 2 - Black screen on video call

### ISSUE THREAD

**Issue by YugiFanGX** [nextcloud/talk-android#657] opened 2019-10-14 18:14 UTC
When starting a video conversation, Nextcloud Talk shows me a black screen with a long small rechtangle from top to bottom on the right side. But at least the buttons for microphone etc. are avaiIable. guess this only occurs on Fairphone 2 devices, as they had difficulties (?) implementing the camera functions correctly. Switching from front to back camera doesn't change anything.

I would be willing to look further into it, but I don't have any programming skills.

**Comment by mario** [comment] 2019-10-14 18:18
I wish I could fix this, but I really don't have the device :(

**Comment by YugiFanGX** [comment] 2019-10-14 18:21
Maybe  @jancborchardt ? Found him on a different closed issue.

**Comment by jancborchardt** [comment] 2019-10-14 19:06
Yeah @YugiFanGX, I do have a Fairphone 2 as well. I can’t reproduce the issue though, it works fine for me with the front-camera. The regular camera of my phone is not working at all, so can’t confirm or deny anything there. ;)

**Comment by mario** [comment] 2019-12-19 22:18
Since neither @jancborchardt nor me can't reproduce, I'll close it for now - let me know if you manage to find a way for me to test this :(

**Closed by mario** 2019-12-19 22:18 UTC
