### ISSUE TITLE
request: to see the userstatus would be nice

### ISSUE THREAD

**Issue by borwinius** [nextcloud/talk-android#942] opened 2020-11-23 11:48 UTC
in talk in a webbrowser i can see the userstatus with a green point.
it would be nice if i also could see this in the android-app.
I found that the SVG-File "/apps/user_status/img/user-status-online.svg" will be loaded with the avatar of the user and  will be displayed

**Comment by nickvergessen** [comment] 2021-05-19 12:17
Duplicate of #898

**Closed by nickvergessen** 2021-05-19 12:17 UTC
Labels: enhancement
