### ISSUE TITLE
Notification sound mixup

### ISSUE THREAD

**Issue by RandomBloke85** [nextcloud/talk-android#1253] opened 2021-05-15 14:25 UTC
Hello

I've changed the default notification sound. Now the default sound AND the changed tone sound together (or afterwards) instead of only the new one (or the one i've changed to).

Samsung S10+, Android 11

Thank you

**Comment by jakobroehrl** [comment] 2021-05-16 11:43
This is the same issues as here described, I think,
https://github.com/nextcloud/talk-android/issues/756

**Comment by mahibi** [comment] 2021-05-17 07:21
thanks for the report @RandomBloke85 
yes seems like a duplicate of #756

**Closed by mahibi** 2021-05-17 07:21 UTC
Labels: bug, feature: 🔔 notifications
