### ISSUE TITLE
send raise hand signaling messages

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2783] opened 2023-02-20 12:19 UTC
in https://github.com/nextcloud/talk-android/pull/2715 the UI for raise hand and request assistance for breakout rooms was introduced.
However, the signaling messages for raise hands are not yet sent. 
This still needs to be implemented, see:

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L425

https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java#L193

**Comment by nickvergessen** [comment] 2023-02-21 08:10
Duplicate of #1056

**Closed by nickvergessen** 2023-02-21 08:10 UTC
Labels: enhancement, 1. to develop
