### ISSUE TITLE
App cannot join to rooms if it is in an erroneous state (workaround: restarting the app)

### ISSUE THREAD

**Issue by goekce** [nextcloud/talk-android#1617] opened 2021-10-06 07:39 UTC
## Steps to reproduce
1. Initiate a one-to-one call on Talk Web interface
2. (no call notification on talk-android, or there is call notification) join the call with your talk-android
(3. disconnect and rejoin)

or

1. Initiate a one-to-one call on Talk Web interface
2. (there is call notification on talk-android) join the call with your talk-android :iphone:  (connection established and everything fine)
3. hang up using talk-android :iphone: 
4. join call again using talk-android :iphone:

### Expected behaviour

talk-android joins the call

### Actual behaviour

talk-android keeps ringing (or keeps showing `INCOMING`)

## Device information

**Device:** Motorola XT1900-7 and Sony G8341

**Android version:** 10 and 9, respectively

**Talk version:** 12.2.1

## Server information

**Nextcloud version:** 22.2.0

**Talk version:** 12.2.0

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server logs (data/nextcloud.log, signaling)

I could not see something special in nextcloud.log. I looked into the signaling server logs instead. I can see that the room is created successfully by the Web client, but there seems to be no connection from talk-android :iphone: to the signaling server. When I close the talk-android :iphone: using App list (right swipe) and start it again, I see the following logs, and the app can join the conference:

```
$ journalctl -xe -u signaling
```

<details>
<pre><samp>

Oct 06 09:17:40 s signaling[15921]: client.go:279: Client from IP-TALK-ANDROID has RTT of 32 ms (32.452629ms)
Oct 06 09:17:40 s signaling[15921]: client.go:279: Client from IP-TALK-ANDROID has RTT of 65 ms (65.637364ms)
Oct 06 09:17:40 s signaling[15921]: hub.go:721: Register user goekce@backend-id from IP-TALK-ANDROID in unknown-country (Mozilla/5.0 (Android) Nextcloud-Talk v12.2.1) 9q1qBdrU1D2Elq7gAbvoMY_ndPKFA0oWwg5I6D4B_Qt8PUFjbEFxMzk0WS1TdTFfQkZjWU9KREVFTTlsd1lrMHY1X0NNbWtKbHo0OGd1RGVoa0ZNV05RckpPTnQ3ZGRBdThTOTc5bkI0TXlyOUk4dVFLTGFmNUQyQ0tqTGo2NEVxZmF4c2NhOFdTbENyLWp0ZE0wNmN3eVlUbF9aWXY5dzZhNHFNY01TWnZZTGVLRkI5cG1sOGktMVA5SUVfTHVWOEFVdXUybjA2YTFQc21KeXl8MDY2NDA1MzM2MQ== (private=MTYzMzUwNDY2MHxXVzJ5U05la2ZPd19VemppeTltQXRyeGxrazR5WUtCcHRZTjRqLWpmbll2d3V3a1cxNlBGSzFhQm90NGpJY2hOOWx3VUVoOFFnNTV4blI1YWZNZHV3WnU5bnF0U3cxZU5QMG1xUTRJbThqeWtqSDVTcTY0U3JWRDJhd1J2NjFwVWEyREhCSGg3VlRSY2xCVzhndm0zSU5nb0x2UkZPN0Q0Nm5CTDVPVmYzWFpoa3I4PXwWSs-D6NFotK3ZhC7NGHVy-pElMDaJ954MxYQbF9ra3A==)
Oct 06 09:17:41 s signaling[15921]: client.go:299: Error reading from IP-TALK-ANDROID: websocket: close 1006 (abnormal closure): unexpected EOF
Oct 06 09:17:41 s signaling[15921]: client.go:297: Error reading from client 9q1qBdrU1D2Elq7gAbvoMY_ndPKFA0oWwg5I6D4B_Qt8PUFjbEFxMzk0WS1TdTFfQkZjWU9KREVFTTlsd1lrMHY1X0NNbWtKbHo0OGd1RGVoa0ZNV05RckpPTnQ3ZGRBdThTOTc5bkI0TXlyOUk4dVFLTGFmNUQyQ0tqTGo2NEVxZmF4c2NhOFdTbENyLWp0ZE0wNmN3eVlUbF9aWXY5dzZhNHFNY01TWnZZTGVLRkI5cG1sOGktMVA5SUVfTHVWOEFVdXUybjA2YTFQc21KeXl8MDY2NDA1MzM2MQ==: websocket: close 1006 (abnormal closure): unexpected EOF
Oct 06 09:17:41 s signaling[15921]: hub.go:782: Unregister 9q1qBdrU1D2Elq7gAbvoMY_ndPKFA0oWwg5I6D4B_Qt8PUFjbEFxMzk0WS1TdTFfQkZjWU9KREVFTTlsd1lrMHY1X0NNbWtKbHo0OGd1RGVoa0ZNV05RckpPTnQ3ZGRBdThTOTc5bkI0TXlyOUk4dVFLTGFmNUQyQ0tqTGo2NEVxZmF4c2NhOFdTbENyLWp0ZE0wNmN3eVlUbF9aWXY5dzZhNHFNY01TWnZZTGVLRkI5cG1sOGktMVA5SUVfTHVWOEFVdXUybjA2YTFQc21KeXl8MDY2NDA1MzM2MQ== (private=MTYzMzUwNDY2MHxXVzJ5U05la2ZPd19VemppeTltQXRyeGxrazR5WUtCcHRZTjRqLWpmbll2d3V3a1cxNlBGSzFhQm90NGpJY2hOOWx3VUVoOFFnNTV4blI1YWZNZHV3WnU5bnF0U3cxZU5QMG1xUTRJbThqeWtqSDVTcTY0U3JWRDJhd1J2NjFwVWEyREhCSGg3VlRSY2xCVzhndm0zSU5nb0x2UkZPN0Q0Nm5CTDVPVmYzWFpoa3I4PXwWSs-D6NFotK3ZhC7NGHVy-pElMDaJ954MxYQbF9ra3A==)
Oct 06 09:17:44 s signaling[15921]: client.go:279: Client from IP-TALK-ANDROID has RTT of 65 ms (65.6789ms)
Oct 06 09:17:44 s signaling[15921]: hub.go:721: Register user goekce@backend-id from IP-TALK-ANDROID in unknown-country (Mozilla/5.0 (Android) Nextcloud-Talk v12.2.1) ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== (private=MTYzMzUwNDY2NHxkYUNtZkF5ZzNDdUhOeEJlNTI3ZHpWMmx1MEdnM3hDZl8yOWs5ZlM0U1JGbDlmR01iMW5RQ1RJYURwaXNlcjVVZkdOamZ4enIzN2lPMmlock5qM0h2bDZvVzRaVWw1ME1tUDZZMVdPOEU1Y3lseHhtRUo2NEZiMjVPSTI1MmZvUVMxODJyZVAtNk41aUVKQVpSdm5OLWVVVnhpV1IwYXVHNG9nWUotX1FoM19yZnZFPXx1UZD4eJmqvJiZsFTTyIjeaOOlnyeAO97IDLONYJxq1w==)
Oct 06 09:17:47 s signaling[15921]: clientsession.go:418: Session ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== joined room 7w49orvj with room session id 68drg7WwzVn0QxasTrwe6NKX4fz9iHw9/j5Qsql4/skjFMFftFfyxcdx4k3niqkiWEcQ/0sDwbGojr23Zb8xQBqYpzskjPHRvhfHFFssSVnJH5lyghmtd8xOk7/ZeAlSOOV3+UFWz2B2OCV+5INvNxSbr4VeIv9t3rIgD0OjY9pQjpbsqgqjdepp9iz8vGIOJq8qM5EniJfozAVKj7B1hkT6+GnwXlJGcWCF3dtoiIrKClN02s5y1IVEQFmcjNc
Oct 06 09:17:47 s signaling[15921]: clientsession.go:234: Permissions of session ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== changed: [publish-media publish-screen control]
Oct 06 09:18:11 s signaling[15921]: hub.go:571: Closing expired session 9q1qBdrU1D2Elq7gAbvoMY_ndPKFA0oWwg5I6D4B_Qt8PUFjbEFxMzk0WS1TdTFfQkZjWU9KREVFTTlsd1lrMHY1X0NNbWtKbHo0OGd1RGVoa0ZNV05RckpPTnQ3ZGRBdThTOTc5bkI0TXlyOUk4dVFLTGFmNUQyQ0tqTGo2NEVxZmF4c2NhOFdTbENyLWp0ZE0wNmN3eVlUbF9aWXY5dzZhNHFNY01TWnZZTGVLRkI5cG1sOGktMVA5SUVfTHVWOEFVdXUybjA2YTFQc21KeXl8MDY2NDA1MzM2MQ== (private=MTYzMzUwNDY2MHxXVzJ5U05la2ZPd19VemppeTltQXRyeGxrazR5WUtCcHRZTjRqLWpmbll2d3V3a1cxNlBGSzFhQm90NGpJY2hOOWx3VUVoOFFnNTV4blI1YWZNZHV3WnU5bnF0U3cxZU5QMG1xUTRJbThqeWtqSDVTcTY0U3JWRDJhd1J2NjFwVWEyREhCSGg3VlRSY2xCVzhndm0zSU5nb0x2UkZPN0Q0Nm5CTDVPVmYzWFpoa3I4PXwWSs-D6NFotK3ZhC7NGHVy-pElMDaJ954MxYQbF9ra3A==)
Oct 06 09:18:24 s signaling[15921]: client.go:277: Client eNnaQQQ3Eho3rS7T_XsGA2tgIP1BJf-gVcvDBUJDFEp8PWdnQTFPbk81d1lnRldWSTRvb0tuZ2NnSFl0YTIwMnZDTkdPbExyakNlSU9LNjFnMkFWdkN2SGwyakNZQVZReVVTSVVNdklFVTJzZGc0TkNtbl9Mb0E5M1FvSUNVSFEwSXF3VHhsNGJUNjNtRldWOWh5Ykp2TzhuY0gycExjZkd1MkdTS1p6ci1hcjlSM1VxVWhnTUthN0lvWHJUSFRvTDBtckRhN2VJZjc3V29iLWp8MDgzNDA1MzM2MQ== has RTT of 11 ms (11.154242ms)
Oct 06 09:18:33 s signaling[15921]: room.go:572: Session ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== joined call 7w49orvj
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:726: Attached video as publisher 4415092854682697 to plugin janus.plugin.videoroom in session 2414074790781363
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:764: Created room 7787877835544718 {janus.plugin.videoroom map[permanent:false room:7787877835544718 videoroom:created]}
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:820: Publisher ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== is using handle 4415092854682697
Oct 06 09:18:33 s signaling[15921]: clientsession.go:692: Publishing video as 48 for session ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ==
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:1005: Attached subscriber to room 7787877835544718 of publisher ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== in plugin janus.plugin.videoroom in session 2414074790781363 as 6778636722734558
Oct 06 09:18:33 s signaling[15921]: clientsession.go:733: Subscribing video from ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== as 49 in session eNnaQQQ3Eho3rS7T_XsGA2tgIP1BJf-gVcvDBUJDFEp8PWdnQTFPbk81d1lnRldWSTRvb0tuZ2NnSFl0YTIwMnZDTkdPbExyakNlSU9LNjFnMkFWdkN2SGwyakNZQVZReVVTSVVNdklFVTJzZGc0TkNtbl9Mb0E5M1FvSUNVSFEwSXF3VHhsNGJUNjNtRldWOWh5Ykp2TzhuY0gycExjZkd1MkdTS1p6ci1hcjlSM1VxVWhnTUthN0lvWHJUSFRvTDBtckRhN2VJZjc3V29iLWp8MDgzNDA1MzM2MQ==
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:1005: Attached subscriber to room 5075426037058237 of publisher eNnaQQQ3Eho3rS7T_XsGA2tgIP1BJf-gVcvDBUJDFEp8PWdnQTFPbk81d1lnRldWSTRvb0tuZ2NnSFl0YTIwMnZDTkdPbExyakNlSU9LNjFnMkFWdkN2SGwyakNZQVZReVVTSVVNdklFVTJzZGc0TkNtbl9Mb0E5M1FvSUNVSFEwSXF3VHhsNGJUNjNtRldWOWh5Ykp2TzhuY0gycExjZkd1MkdTS1p6ci1hcjlSM1VxVWhnTUthN0lvWHJUSFRvTDBtckRhN2VJZjc3V29iLWp8MDgzNDA1MzM2MQ== in plugin janus.plugin.videoroom in session 2414074790781363 as 2885996456779323
Oct 06 09:18:33 s signaling[15921]: clientsession.go:733: Subscribing video from eNnaQQQ3Eho3rS7T_XsGA2tgIP1BJf-gVcvDBUJDFEp8PWdnQTFPbk81d1lnRldWSTRvb0tuZ2NnSFl0YTIwMnZDTkdPbExyakNlSU9LNjFnMkFWdkN2SGwyakNZQVZReVVTSVVNdklFVTJzZGc0TkNtbl9Mb0E5M1FvSUNVSFEwSXF3VHhsNGJUNjNtRldWOWh5Ykp2TzhuY0gycExjZkd1MkdTS1p6ci1hcjlSM1VxVWhnTUthN0lvWHJUSFRvTDBtckRhN2VJZjc3V29iLWp8MDgzNDA1MzM2MQ== as 50 in session ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ==
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:553: Started listener &{{janus.plugin.videoroom map[room:7787877835544718 started:ok videoroom:event]} map[] 2414074790781363 6778636722734558}
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:553: Started listener &{{janus.plugin.videoroom map[room:5075426037058237 started:ok videoroom:event]} map[] 2414074790781363 2885996456779323}
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:1082: Subscriber 6778636722734558 received connected
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:859: Publisher 4415092854682697 received connected
Oct 06 09:18:33 s signaling[15921]: mcu_janus.go:1082: Subscriber 2885996456779323 received connected
Oct 06 09:18:35 s signaling[15921]: mcu_janus.go:849: Publisher 4415092854682697 received hangup (DTLS alert), closing
Oct 06 09:18:35 s signaling[15921]: mcu_janus.go:836: Publisher 4415092854682697: associated room has been destroyed, closing
Oct 06 09:18:35 s signaling[15921]: mcu_janus.go:909: Room 7787877835544718 destroyed
Oct 06 09:18:35 s signaling[15921]: mcu_janus.go:1072: Subscriber 6778636722734558 received hangup (Close PC), closing
Oct 06 09:18:35 s signaling[15921]: janus_client.go:472: Unable to deliver message {
                                       "janus": "detached",
                                       "session_id": 2414074790781363,
                                       "sender": 6778636722734558
                                    }. Handle 6778636722734558 gone?
Oct 06 09:18:35 s signaling[15921]: janus_client.go:472: Unable to deliver message {
                                       "janus": "detached",
                                       "session_id": 2414074790781363,
                                       "sender": 4415092854682697
                                    }. Handle 4415092854682697 gone?
Oct 06 09:18:35 s signaling[15921]: clientsession.go:432: Session ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== left call 7w49orvj
Oct 06 09:18:36 s signaling[15921]: hub.go:782: Unregister ZkwKroa2I_-3UZSKUr_v0q0HmebE0bVVKYGFjis1Aqt8PWNISWhrcXVjSGZBeFZ0dW9wSzBsOEFNQk9DUDdNdlNCQk1vdUh1T21MVDFjRzM5R3FqazJKNDFQcUhMckFCZDg0TU9tVmtac0lvNURlR19FbDNLQ20yeDNiSzV0SndsTmZKR2VtcUtmQ3hnUVE0S1pfckZ4dHlFdy1PX3U0cnZCUERoVkx5eHR5UFdDNkwzOHlWTk9INk9VdWRXOGRYMFFEZ1EtejJzcEtUYUNLZEl8NDY2NDA1MzM2MQ== (private=MTYzMzUwNDY2NHxkYUNtZkF5ZzNDdUhOeEJlNTI3ZHpWMmx1MEdnM3hDZl8yOWs5ZlM0U1JGbDlmR01iMW5RQ1RJYURwaXNlcjVVZkdOamZ4enIzN2lPMmlock5qM0h2bDZvVzRaVWw1ME1tUDZZMVdPOEU1Y3lseHhtRUo2NEZiMjVPSTI1MmZvUVMxODJyZVAtNk41aUVKQVpSdm5OLWVVVnhpV1IwYXVHNG9nWUotX1FoM19yZnZFPXx1UZD4eJmqvJiZsFTTyIjeaOOlnyeAO97IDLONYJxq1w==)
Oct 06 09:18:36 s signaling[15921]: client.go:299: Error reading from IP-TALK-ANDROID: read tcp 127.0.0.1:8080->127.0.0.1:52036: use of closed network connection
Oct 06 09:18:36 s signaling[15921]: clientsession.go:478: Removed room session 68drg7WwzVn0QxasTrwe6NKX4fz9iHw9/j5Qsql4/skjFMFftFfyxcdx4k3niqkiWEcQ/0sDwbGojr23Zb8xQBqYpzskjPHRvhfHFFssSVnJH5lyghmtd8xOk7/ZeAlSOOV3+UFWz2B2OCV+5INvNxSbr4VeIv9t3rIgD0OjY9pQjpbsqgqjdepp9iz8vGIOJq8qM5EniJfozAVKj7B1hkT6+GnwXlJGcWCF3dtoiIrKClN02s5y1IVEQFmcjNc: map[error:map[code:no_such_room message:The user is not invited to this room.] type:error]
</samp></pre>
</details>

After this talk-android :iphone: cannot join the call again unless I restart the app, but there are messages about joining/leaving in the chat window. Talk-android seems to stay in this state for a long time (until it is restarted by Android?).

Did someone have a similar issue or can someone verify this?

I also searched in the issues, https://github.com/nextcloud/talk-android/issues/1328 seems to be related.

**Comment by mahibi** [comment] 2021-10-06 08:47
thanks for the report @goekce 
This is a duplicate of https://github.com/nextcloud/talk-android/issues/1232 so i will close this issue.
The problem is known, it's caused by https://github.com/nextcloud/talk-android/issues/1582
we are working on a solution!

**Closed by mahibi** 2021-10-06 08:47 UTC
Labels: bug, 0. Needs triage
