### ISSUE TITLE
Unified Search in Talk App

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/talk-android#1790] opened 2022-01-28 11:43 UTC
### Is your feature request related to a problem? Please describe.
Not sure if this is a feature or a bug. When I use Talk in the browser and type a keyword in search it searches all chats and shows me all messages that contain that keyword.

When i do the same on the app it does not search the chat messages. instead it only seaches names of users and channels.

### Describe the solution you'd like
If i search for a keyword it should show me all messages that contain the keyword.

### Describe alternatives you've considered
none

### Additional context
Informations about Unified search: https://nextcloud.com/unified-search/ - but within the talk ab it should only search talk-objects.

**Comment by mahibi** [comment] 2022-01-28 13:17
the unified search like in the browser is not implemented in the talk app but this of course would make sense.
i will close this as duplicate of https://github.com/nextcloud/talk-android/issues/1047

**Closed by mahibi** 2022-01-28 13:17 UTC
Labels: enhancement, 0. Needs triage
