### ISSUE TITLE
Talk 14.2.0 rc2 loads blank.

### ISSUE THREAD

**Issue by small1** [nextcloud/talk-android#2322] opened 2022-08-22 12:26 UTC
### Steps to reproduce

1. Open talk
2. No list of conversations Cant change server or settings. UI is blank
<img width="300" src="https://user-images.githubusercontent.com/317830/185919516-40ab4952-6843-45e8-ad50-a6442b737a8e.jpg" />

### Expected behaviour

Open talk and see a list of conversations.  

### Actual behaviour

Talk opens  blank. And if i choose to create a conversation it crashes

### Device brand and model

Oneplus 9 pro

### Android version

12

### Nextcloud Talk app version

14.2.0 rc1

### Nextcloud server version

24.0.4

### Talk version

14.0,4

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

Connected to three different servers.

Two Nextcloud 24.0.4 with talk 14.0.4  with an external hpb and turn server. Both are pretty identical.
One is the nextcloud.com instance.

**Comment by mahibi** [comment] 2022-08-22 12:33
can you try with other phones and see if this problem occurs as well?

**Comment by small1** [comment] 2022-08-22 12:43
My own two instances work. I cant add the nextcloud.com one since 2fa is broken for guest users at the moment. I'll try another phone and see if that also breaks.

**Comment by mahibi** [comment] 2022-08-22 12:50
i just tried out nextcloud.com with another guest account. I get the error "unsupported server". So this might be related. i will have a closer look!

**Comment by mahibi** [comment] 2022-08-26 06:19
> i just tried out nextcloud.com with another guest account. I get the error "unsupported server". So this might be related. i will have a closer look!

can't reproduce this anymore :confused:

**Comment by mahibi** [comment] 2022-08-26 06:19
@small1 just to sum up here what was discussed in chat:
this happens because you try to use webauthn?

**Comment by small1** [comment] 2022-08-26 07:04
I reproduced this on one more oneplus. It happens when its upgraded from another version to 4.2.0 rc2  but once storage is wiped  and accounts are added back it works as it should again.

It has nothing tod o with 2fa. The 2fa stuff was noticed when i readded the accounts that ive had for quite some time and was setup with older 2fa app.  so webauthn is a completly other type of bug

**Comment by AndyScherzinger** [comment] 2022-08-26 10:58
@small1 what is the version you are upgrading from?

**Comment by AndyScherzinger** [comment] 2022-08-31 10:20
So @timkrueger and I tested various paths, most important, 
* 14.0->14.2
* 13.0->14.2

without any issues, so we can't reproduce this issue. The empty screen comes up if the client can't load any talk data since the Android app currently doesn't have any offline capabilities so all data gets fetched from server or if you would face some database issues where we can't retrieve the user infos or cookies&/session. The big structural change with 14.1 and 14.2 was the complete replacement of the db access layer as well as the cipher upgrade for the db encryption

**Comment by tobiasKaminsky** [comment] 2022-08-31 10:23
An idea would be to show 
- log error in log file
- show an user error: login failed, please click here to re-authenticate

**Comment by small1** [comment] 2022-08-31 13:23
I think i went from 14.2.0rc1 to rc2  or a version before that to 14.2.0 rc2 Im  in the beta channel and i tend to make sure i have updated all apps every week. And it might have been something that has been lurking since an earlier version that that that just exploded in the rc2 version 

So this might not be an issue that will occur later on.

**Comment by small1** [comment] 2022-08-31 13:24
> 

In my case i tested access from my computer and other phone in paralell and broth from wifi and mobile network.  Just to exclude a non reachable server :)

**Comment by YoannPa** [comment] 2022-09-23 04:08
> ### Steps to reproduce
> 1. Open talk
> 2. No list of conversations Cant change server or settings. UI is blank
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/317830/185919516-40ab4952-6843-45e8-ad50-a6442b737a8e.jpg">
> 
> ### Expected behaviour
> Open talk and see a list of conversations.
> 
> ### Actual behaviour
> Talk opens blank. And if i choose to create a conversation it crashes
> 
> ### Device brand and model
> Oneplus 9 pro
> 
> ### Android version
> 12
> 
> ### Nextcloud Talk app version
> 14.2.0 rc1
> 
> ### Nextcloud server version
> 24.0.4
> 
> ### Talk version
> 14.0,4
> 
> ### Custom Signaling server configured
> Yes (specify version in Additional Information)
> 
> ### Custom TURN server configured
> Yes
> 
> ### Custom STUN server configured
> Yes
> 
> ### Android logs
> _No response_
> 
> ### Server log
> _No response_
> 
> ### Additional information
> Connected to three different servers.
> 
> Two Nextcloud 24.0.4 with talk 14.0.4 with an external hpb and turn server. Both are pretty identical. One is the nextcloud.com instance.

I have set up a Nextcloud server, and some of our Nextcloud Talk users on smartphone are experiencing the same issue since the **update of Nextcloud toward 24.0.4**.
They cannot load conversations, or access them, unless they wait for a long time enough.

From users reports, **this seems to happen both under iOS for IPhone users, and Android.**
**All users are not impacted with the same severity** : Maybe those who have a longer history of use have to wait for a longer time when opening the app ?

Displaying an info dialog would be nice of course, but more important: what should we recommend the users to do in such case ?
Should we ask them to reinstall the Nextcloud Talk app ?

Thanks a lot for all the information shared here and the incredible job you're doing !

**Comment by mahibi** [comment] 2023-01-11 09:02
is this still an issue or is it fixed with the latest version?

**Comment by small1** [comment] 2023-01-11 11:26
It seems to be fixed.

I can't reproduce it anymore.

**Comment by YoannPa** [comment] 2023-01-11 17:46
Most users not complaining anymore on my side. So... no idea but it sounds positive I guess.

**Closed** 2023-01-16 08:29 UTC
Labels: bug
