### ISSUE TITLE
Ethernet connection on GrapheneOS gives "Please check you internet connection"

### ISSUE THREAD

**Issue by johan0322** [nextcloud/talk-android#3988] opened 2024-07-01 16:15 UTC
### Steps to reproduce

1. Open NextCloud Talk on GrapheneOS with a working wifi connection
2. Connect to ethernet via usb-c
3. Wait 10 seconds
4. Refresh app by "swiping down"

Dialog will now show saying "Please check your internet connection"

### Expected behaviour

App should use the wired ethernet connection to refresh

### Actual behaviour

App seems not to be able to use the ethernet connection for refresh

### Device brand and model

Pixel 6a

### Android version

14

### Nextcloud Talk app version

v19.0.1

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment] 2024-07-03 07:07
Thanks for reporting.
This is already fixed but not yet released.

duplicate of https://github.com/nextcloud/talk-android/issues/3896, solved by https://github.com/nextcloud/talk-android/pull/3947

**Closed by mahibi** 2024-07-03 07:07 UTC
Labels: bug, 0. Needs triage
