### ISSUE TITLE
Ability to save or export photos or files 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/talk-android#2386] opened 2022-09-18 21:14 UTC
It would be nice to have an option under share to save photo to phone and export photo like the nextclud app currently the ios talk app has this option ![22-09-18 16-10-32 0045.png](https://user-images.githubusercontent.com/59488153/190928340-2905b4d0-98b6-4443-9534-de367f91eb9c.png)

**Comment by mahibi** [comment] 2022-09-19 08:10
closing as duplicate of https://github.com/nextcloud/talk-android/issues/2331

**Closed by mahibi** 2022-09-19 08:10 UTC
Labels: enhancement, 0. Needs triage
