### ISSUE TITLE
Add option to make different video streams fullscreen

### ISSUE THREAD

**Issue by blitzdose** [nextcloud/talk-android#2680] opened 2023-01-11 23:04 UTC
**Is your feature request related to a problem? Please describe.**
When I do a video call from a browser to the app and share my screen, the App shows my camera and the shared screen side by side.

**Describe the solution you'd like**
It would be great if you could click one of that streams and it goes into fullscreen something like in the browser.

**Describe alternatives you've considered**
For me, it would also be okay if the camera completely disappears when a screen is shared and comes back when the share ends.

**Additional context**
On my phone the call looks like this:
![1673478210193](https://user-images.githubusercontent.com/35041688/211936989-3cbf686a-7276-41fb-b3a2-5d924d3acd16.jpg)

**Comment by mahibi** [comment] 2023-02-20 12:29
duplicate of https://github.com/nextcloud/talk-android/issues/1397

**Closed by mahibi** 2023-02-20 12:29 UTC
Labels: enhancement, 0. Needs triage
