### ISSUE TITLE
android 7.0 Handshake failed (main NC app has fixed it)

### ISSUE THREAD

**Issue by dadosch** [nextcloud/talk-android#676] opened 2019-11-25 16:02 UTC
with android 7.0, there is a bug which needs some workaround sothat ssl functions properly.

This has also been an issue in the main Nextcloud app, but has  been fixed there a while ago.

 In nextcloud-news this has been fixed with https://github.com/nextcloud/news-android/commit/4bad914c82527bdbf50ba01bf7e4c5bd9d1b7d24 I think, but I could find the commit for nextcloud-android.

**Comment by nickvergessen** [comment] 2019-11-25 19:44
Duplicate of #672

**Closed by nickvergessen** 2019-11-25 19:44 UTC
