### ISSUE TITLE
Advise users to set the "Keep running after screen off" atribute

### ISSUE THREAD

**Issue by elpraga** [nextcloud/talk-android#84] opened 2018-01-28 17:43 UTC
If the app gets closed after the screen is locked (default on my phone), calls cannot be received for no (at least to me :disappointed:) apparent reason.

Maybe users should be advised to change the settings? (I might be just a little dumb, might be obvious to others, I'm not sure :rofl: )

**Comment by mario** [comment] 2018-01-28 17:44
This shouldn't be true. I will, however, test it out - assuming I have this setting on one of my phones.

**Comment by elpraga** [comment] 2018-01-28 18:02
I was just testing it again, and I can confirm the behavior. I've got two Huawei devices and they both have this feature (it is called __Don't close after screen off__). Calls don't get through if not set.

The same is true if I forcibly close the app (I guess that's what happen if the attribute is not set, and the screen switches off), the calls are not received.

**Comment by mario** [comment] 2018-01-28 18:26
I just looked, doesn't look like Samsung has it. 

Folks, anyone else has this "feature"?

**Comment by elpraga** [comment] 2018-01-28 21:45
I would guess all Huawei phones and tablets have it..

**Comment by jookk** [comment] 2018-01-29 01:50
Yes, at huawei, this is their battery optimisation - app to app setting. As I know from Android 4.4 to 7.
Xiaomi have miui battery optimisation. App to app too - individually. (I have set it to No savings.)
And other (chinese?) can have their "optimisations" too.

**Comment by mario** [comment] 2018-01-29 01:53
Awesome :-/ Strange ideas about memory and battery management - just kill EVERYTHING *shrug*

**Comment by mario** [comment] 2018-01-29 01:55
@jookk push works for you on Xiaomi?

**Comment by mario** [comment] 2018-01-29 01:56
And would you mind sending me screenshots of this "settings" to mario AT nextcloud.com? Thanks! :)

**Comment by mario** [comment] 2018-01-29 01:57
Same for you @elpraga  ^_^

**Comment by jookk** [comment] 2018-01-29 01:58
Mario, at least, you can require "no batt optimised" android permission. On 
miui (android 7) this permission turn miui optimization off. (we can test)


Dňa 29. januára 2018 2:53:35 AM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by jookk** [comment] 2018-01-29 01:59
Receiving call, you mean? Yes.


Dňa 29. januára 2018 2:55:55 AM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment] 2018-01-29 02:00
@jookk I'll have a test version for you tomorrow. Would appreciate if you can test it on both Huawei and Xiaomi cc @elpraga

**Comment by jookk** [comment] 2018-01-29 02:05
Huawei not possible till friday - at least.



Dňa 29. januára 2018 3:00:17 AM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment] 2018-01-29 02:14
Ah I found a better way to fix this. Gimme a few days :)

**Comment by elpraga** [comment] 2018-01-29 10:39
OK, I can test it on Huawei. I'll send you  the screenshot later on as well!

**Comment by mario** [comment] 2018-01-29 11:00
@elpraga please try push now. With "Keep running after screen off" unset of course!

**Comment by mario** [comment] 2018-01-29 18:51
Same to you @jookk ^_^

**Comment by jookk** [comment] 2018-01-29 18:53
What to do? Is there new version to tedt or Im missing something? :O

**Comment by mario** [comment] 2018-01-29 18:58
No, existing version. Enable all battery optimizations, and remove the check from "Keep running after screen off". Then try calling your phone from another account and see if you get a notification.

**Comment by jookk** [comment] 2018-01-29 20:47
Yes, it worked - got push notification.

**Comment by mario** [comment] 2018-01-29 20:57
Thanks @jookk. Now just waiting for @elpraga to confirm, and we can close the issue :)

**Comment by elpraga** [comment] 2018-01-29 21:03
testing now
.

**Comment by jookk** [comment] 2018-01-29 21:05
Strange (at least for xiaomi) :D


Dňa 29. januára 2018 9:57:47 PM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by elpraga** [comment] 2018-01-29 21:12
before I finish testing.. @jookk  , where are you from? 😄

**Comment by jookk** [comment] 2018-01-29 21:14
Slovakia


Dňa 29. januára 2018 10:12:14 PM používateľ elpraga 
<notifications@github.com> napísal:

**Comment by elpraga** [comment] 2018-01-29 21:23
I was born in Brno, I've been living in Spain for last eleven years..
I keep testing the behaviour, still not working 100%. I'm trying to check all possible options. I'll let you know when I finish..

**Comment by mario** [comment] 2018-01-29 21:24
@elpraga let me know. It really SHOULD work now :)

**Comment by elpraga** [comment] 2018-01-29 21:39
I'll take my time testing @mario . So far i. doesn't work 100, I'll test it thoroughly, I'll try to guess the behaviour in normal use. I'll definitely let you know.

**Comment by elpraga** [comment] 2018-01-29 23:21
Ok. I've got my results.
First, the devices I used for testing:
1. Tablet Huawei MediaPad T10, Android 7.0,  Nextcloud talk 1.1 (the version @mario uploaded here), 
     The battery saving option can be found __Settings__ -> __Battery__ -> __Close apps on screen lock__  -> __Nextcloud Talk__ -> _Unchecked_, text _Won't be closed_ appears under the name of the application. 
2. Phone Huawei Y6II, Android 6.0, Nextcloud talk 1.0.14 (latest Google Play version)
     The battery saving option can be found __Settings__ ->  __Advances settings__ ->  __Battery manager__  -> __Protected apps__  -> __Nextcloud Talk_ -> _Checked_, text _Protected_ appears under the name of the app.

### Calling from the Phone to the Tablet
1. Battery optimisation on (app gets killed)
 - __It is impossible to receive a call even when Nextcloud Talk is open and active__ (yes, I wrote exactly that) - no notification appears.

2. Battery optimisation off (app protected)
Calls are received (even after restart and when Nextcloud talk hasn't been used yet)

### Calling from the Tablet to the Phone
1. Battery optimisation on (app gets killed)
imposible to receive calls after restart if app not used previously. When app used, calls can be received (notification appears) until the screen locks. 

2. Battery optimisation off (app protected)
Calls are received (even after restart and when Nextcloud talk hasn't been used yet)

- If Nextcloud talk is forcebly killed (Force Quit), calls are not received (no notification)


Note: It should be possible to set this attribute automatically upon install. There are some apps that are protected, but I'm sure I haven't  switched the protection on manually (A.I. Floating Keyboard for example). In my opinion, it would be good to set this attribute (whatever it is called) upon install to ensure proper function.

I hope my testing helps!!

**Comment by mario** [comment] 2018-01-30 06:40
Thanks for testing @elpraga. Disappointing results, since the way we do push, should pierce even through battery optimizations, but it is what it is.

It is possible to ASK for you to ignore battery optimizations, but not really recommended by Google. Let me see if we'd fall into the exceptions category.

**Comment by mario** [comment] 2018-01-30 06:42
@jookk you tried with Xiaomi, right?

**Comment by jookk** [comment] 2018-01-30 07:04
Yes, with xiaomi, android 7, miui9.
Its strange, because I have more apps with miui batt optimisations off. 
(nextcloud, davdroid...)
Maybe, on miui8 android6 miui batt optimisations was stricter.

I now tried calling after reboot and Talk app ringed.


Dňa 30. januára 2018 7:42:33 AM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment] 2018-01-30 07:55
@elpraga when you disabled battery optimisations, did you also tick the app under Autostart apps?

**Comment by elpraga** [comment] 2018-01-30 08:28
No, I haven't. I don't even know where to look for Autostart apps.

What really surprises me is that I'm not able to receive __any calls__ (not even with the app open and focused) on the tablet with Android 7.0 unless I uncheck the Close app on Screen Lock

**Comment by mario** [comment] 2018-01-30 08:32
@elpraga this Huawei stuff is worse than Xiaomi :( At least it works on Xiaomi, as @jookk confirmed.

**Comment by elpraga** [comment] 2018-01-30 08:58
You're right :(

**Comment by mario** [comment] 2018-01-30 12:06
@jookk did you try to force close the app and see if you get notifications then with battery optimizations on?

**Comment by mario** [comment] 2018-01-30 12:07
@elpraga since this seems to be a platform bug, not much I can do on Huawei :( Bug them? :P

**Comment by mario** [comment] 2018-01-30 12:16
@elpraga did you set your app as "protected" btw?

**Comment by jookk** [comment] 2018-01-30 12:21
Actually I cant force close talk
See button on bottom of the screen "Ukončiť" grey.


Dňa 30. januára 2018 1:06:50 PM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment] 2018-01-30 12:22
@jookk sent me an email with screenshot or?

**Comment by jookk** [comment] 2018-01-30 12:23
Yes


Dňa 30. januára 2018 1:22:11 PM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment] 2018-01-30 12:23
OK, waiting :)

**Comment by mario** [comment] 2018-01-30 13:28
@elpraga could you look into Settings > All, and choose Startup manager.?

**Comment by elpraga** [comment] 2018-01-30 21:05
I haven't got anything similar in the Settings. Are you sure it is a standard part of Android install?

**Comment by elpraga** [comment] 2018-01-30 21:14
I don't have anything like "Protected", both names are different, but I can set don't close after screen off thing. I'm not sure if bugging Huawei is the way to go, can talk get the exception you talked about? Maybe stating this example would help?

**Comment by elpraga** [comment] 2018-01-30 21:17
Or can talk check if it's running in a Huawei device,  check if this permission is set, and if not, prompt the user to set it manually?

**Comment by mario** [comment] 2018-01-30 22:24
@elpraga it can check if it's Huawei, but not if it has proper stuff set. Didn't you say setting "Keep running after screen off" doesn't help when you kill the app though? :(

**Comment by mario** [comment] 2018-01-31 01:10
@elpraga Settings -> Advanced settings -> Battery manager -> Protected apps ? :)

**Comment by mario** [comment] 2018-01-31 01:39
@elpraga also I got one idea that you can test (for not receiving notifications when you swipe). APK in a sec.

**Comment by mario** [comment] 2018-01-31 01:41
@elpraga http://172.104.243.61/nextcloud/index.php/s/j4oRkb9PyXZtGqN 
Same to you @jookk  :)

**Comment by mario** [comment] 2018-01-31 01:41
Test with and without battery optimizations, swiping, rebooting etc :)
Thanks! :)

**Comment by jookk** [comment] 2018-01-31 06:39
Wow! Great!
Bigger buttons, room actions! Fine :)
Updated talk, phone reboot, batt opt. off, autostart on - > call 
notification worked, video, audio fine.

Switched off autostart, miui batt opt. ON, Phone reboot - > no call 
notification.

Tried room actions - working fine

Issue with buttons when in call. (calling in progress) impossible to show 
buttons. They are there, but not visible. (I know, because I ended call by 
tapping to invisiible red button)

Xiaomi, android 7, miui9


Dňa 31. januára 2018 2:41:44 AM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment] 2018-01-31 07:12
Hey, don't try the other features haha xD

Thanks for testing, so it really looks like there's nothing we can do.

Google considers "force close" means you don't want any more notifications, so *shrug* :)

**Comment by elpraga** [comment] 2018-01-31 12:55
I'm off to work now. I hope to be able to have a look at it after work!

I'll let you know.

**Comment by elpraga** [comment] 2018-02-01 00:42
exactly the same behaviour as before @mario 

Great to see the call options! I have to admit that i had problems with the …  button. Sometimes it wouldn't work, sometimes it would start the call instead..

great work!

**Comment by mario** [comment] 2018-02-01 14:05
I found a way to detect if autostart is enabled on Xiaomi. Now to find a way to see if I can detect "Keep running after screen off" ...

**Comment by jookk** [comment] 2018-02-01 14:07
Good! 🤞


Dňa 1. februára 2018 3:05:59 PM používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by jookk** [comment] 2018-02-01 18:31
At Huawei (I think) this is not standard android os feature. If you @mario want to test batt optimisation off permission @elpraga can test it. If this helps to resolve screen off issue on huawei.

**Comment by elpraga** [comment] 2018-02-01 21:24
It does seem that the __Keep running after screen off__ option on Huawei also autostarts the app. As I mentioned previously, A.I. Floating Keyboard set it up upon install (there might be many more, this is the one I know off).

And yes, I can help to test it @mario

**Comment by mario** [comment] 2018-02-08 00:51
So I have a special Huawei APK built now at http://172.104.243.61/nextcloud/index.php/s/NNbaLtHE4PAEo75

How to test:
- enable all battery optimizations
- make sure Keep runinng after screen off is NOT ticked
- make sure Autoboot is NOT ticked
- start the app

Keep in mind, since I'm coding blindly, the app might crash and burn. HOWEVER!

Even if it does that, please make sure after you've ran it, to check if:
- battery optimizations were disabled
- keep running after screen off is ticked
- start on boot is ticked

Thanks @elpraga and @jookk

**Comment by jookk** [comment] 2018-02-08 05:50
I have test that apk also?

**Comment by mario** [comment] 2018-02-08 07:18
Only if you have huawei :)

**Comment by mario** [comment] 2018-02-08 16:15
New APK: http://172.104.243.61/nextcloud/index.php/s/xGfX4b6QxK7BNmw

**Comment by elpraga** [comment] 2018-02-08 21:21
I'll try it out as soon as I can Mario!

**Comment by mario** [comment] 2018-02-16 13:13
@elpraga news? :)

**Comment by elpraga** [comment] 2018-02-18 22:16
I'm sorry @mario , I've been quite busy lately. I did notice a change when using the Huawei with Marshmallow 6.0.  It worked out of the box. Nonetheless there was no difference in behaviour on the Android 7.0 on my tablet. 

I've installed _Termux_ recently, and it did install as a _protected app_ out of the box. They even mention that the app needs to be __protected__ on their website. I'm not sure if that helps.

**Comment by mario** [comment] 2018-02-19 00:08
@elpraga and @jookk , please test http://172.104.243.61/nextcloud/index.php/s/4XLcai2cDrTgTfg as soon as you can.

Steps:
0) Unset app as protected and remove "Autostart"

1) Remove the existing app
2) Install this one
3) Run the app

Xiaomi:
4) Check if app autostart is enabled
5) ??

Huawei:
4) Check if app is set as Protected
5) ??

Thanks!

**Comment by jookk** [comment] 2018-02-19 01:55
Removed autostart
Cleared app data
Uninstall
Downloaded new apk
Installed
First run
Imported account
Back
Checked app permissions and Autostart not enabled


Dňa 19. februára 2018 1:08:43 AM používateľ Mario Đanić 
<notifications@github.com> napísal:>

**Comment by mario** [comment] 2018-02-19 02:33
Thanks @jookk. New APK: http://172.104.243.61/nextcloud/index.php/s/BzXZfc6eFR3NABw

**Comment by jookk** [comment] 2018-02-19 05:36
Cant be run. FC all the time

Dňa 19. februára 2018 3:33:03 AM používateľ Mario Đanić 
<notifications@github.com> napísal:>

**Comment by mario** [comment] 2018-02-19 08:44
FC? XD

**Comment by mario** [comment] 2018-02-19 09:28
@jookk sounds strange, runs for me (but I don't have xiaomi).

http://172.104.243.61/nextcloud/index.php/s/BzXZfc6eFR3NABw

Same url, different APK :)

**Comment by jookk** [comment] 2018-02-19 10:02
App started, autostart not enabled.

Dňa 19. februára 2018 10:28:13 AM používateľ Mario Đanić 
<notifications@github.com> napísal:>

**Comment by mario** [comment] 2018-02-19 10:13
:( Sad day. Did you try to reboot to see if it maybe changes? xD

**Comment by jookk** [comment] 2018-02-19 10:18
No, I did without reboot. I try

Dňa 19. februára 2018 11:13:44 AM používateľ Mario Đanić 
<notifications@github.com> napísal:>

**Comment by jookk** [comment] 2018-02-19 10:30
Mario, can you send me apk which fc for me? I rebooted and I have mishmatch 
with apks :D
Thx

Dňa 19. februára 2018 11:13:44 AM používateľ Mario Đanić 
<notifications@github.com> napísal:>

**Comment by mario** [comment] 2018-02-19 10:31
Uh I don't think so xD I deleted that one already :-/

Can you mail me btw? Easier to talk that way! :)

**Comment by mario** [comment] 2018-02-19 12:05
@jookk same url, new APK :P

**Comment by jookk** [comment] 2018-02-19 12:41
Autostart not enabled, running ok

Dňa 19. februára 2018 1:05:15 PM používateľ Mario Đanić 
<notifications@github.com> napísal:>

**Comment by mario** [comment] 2018-02-19 15:34
Sad sad @jookk :)

@elpraga let me know when you get a chance to test latest APK!

**Comment by mario** [comment] 2018-02-19 22:39
@jookk new APK :D

**Comment by jookk** [comment] 2018-02-20 05:34
Good morning,
So:
Cleared app data
Uninstall
Reboot
Install ftom
http://172.104.243.61/nextcloud/index.php/s/BzXZfc6eFR3NABw
App started, imported account
Then autostart not enabled in settings

**Comment by elpraga** [comment] 2018-02-26 01:23
I'm sorry for the delay @mario the last app-GPlay-release.apk works correctly on Android 7.0 - app is protected right after install. The same app is not protected after install on Android 6.0.

Hope it helps.

**Comment by mario** [comment] 2018-02-27 17:58
@elpraga thanks. I'll try to hunt down a 6 phone to see what's wrong :(

@jookk will need a Xiaomi phone to fix this looks like :(

**Comment by mario** [comment] 2018-07-17 18:08
@elpraga and @jookk can you both mail me? Mario AT nextcloud.com

**Comment by mario** [comment] 2019-12-27 09:58
In the mean time this has created a bit less of problems as the HW makers made more sane defaults. Let me know if you still run into issues.

**Closed by mario** 2019-12-27 09:58 UTC
