### ISSUE TITLE
An ongoing call will be interrupted if the Talk app gets in the background.

### ISSUE THREAD

**Issue by Byter3** [nextcloud/talk-android#1713] opened 2021-11-18 02:34 UTC
Hi,

Talk: 13.0.0 RC1
Android: 11
Device: SM-A705FN/DS

Issue:
An ongoing call will be interrupted if the Talk app gets in the background.

Expected behaviour:
The call continues while the app is in the background. Perhaps even a little floating window with the participiants, specially if it's a video call.

I gave the app every possible permission.

**Comment by mahibi** [comment] 2021-11-18 08:40
Did you enable Picture in Picture support in the Android settings?

**Comment by Byter3** [comment] 2021-12-07 03:41
> Did you enable Picture in Picture support for the Talk app in the Android settings?

Hi I did not had that feature when I detected the issue. Yes PIP is working fine, when I specifacly put the call in pip. But still I think the desired result "minimezing"a call is not to hold the call. It can happen excidentally even. So continuing a call in the background would be the fix for this.

**Comment by mahibi** [comment] 2021-12-21 20:22
i fully agree that there has to be a solution for calls in background in addition to PIP.
i will close this issue as it´s a duplicate of https://github.com/nextcloud/talk-android/issues/1688 
feel free to reopen if i got you wrong..

**Closed by mahibi** 2021-12-21 20:22 UTC
