### ISSUE TITLE
Copying messages to clipboard with long press gives no feedback (Was "Cannot copy text messages")

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#307] opened 2018-09-12 13:03 UTC
The text messages should be copyable on long press.

**Comment by mario** [comment] 2018-09-12 13:14
They are?

**Comment by mario** [comment] 2018-09-14 13:49
It's a long press. Did you try long press on the input field and click Paste afterwards?

**Comment by gradinaruvasile** [comment] 2018-09-14 19:30
No. But i did now and it works :)

Anyway it's a "hidden" feature, it works differently than any other app and without any feedback to the user.
So we have 2 issues here:
- The copy operation should provide some feedback, if not else, at least a toast with "copied to clipboard".
- The messages should be copyable partially too. I have some apps that annoyingly let only a full chat message to be copied, if i have something like a telephone number i will have to jump through hoops to extract it (maybe not the best example but this is true for any sub-string).

**Comment by mario** [comment] 2018-09-17 05:59
Hi,

we already have an issue for the first (https://github.com/nextcloud/talk-android/issues/220) and I believe @giulianograssi is working on it - right?. Second please file a separate issue if it's not too much of a problem.

Cheers..

**Comment by jancborchardt** [comment] 2018-10-02 21:57
Duplicate of https://github.com/nextcloud/talk-android/issues/220 → let’s continue there. :)

**Comment by jancborchardt** [comment] 2018-10-02 21:57
Duplicate of https://github.com/nextcloud/talk-android/issues/220 → let’s continue there. :)

**Closed by jancborchardt** 2018-10-02 21:57 UTC
