### ISSUE TITLE
chat header hides when using the tastatur

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1757] opened 2022-01-03 08:46 UTC
https://user-images.githubusercontent.com/24530680/147912756-4764891e-aa4a-4496-809d-90defe8157f3.mp4

Tested on some photes, occures on all of them.

**Comment by mahibi** [comment] 2022-01-03 11:44
this seems to be a duplicate of https://github.com/nextcloud/talk-android/issues/992
i began to analyze/fix this in https://github.com/nextcloud/talk-android/pull/1285 but didn't find the time to continue..

**Closed by mahibi** 2022-01-03 11:44 UTC
Labels: bug, 0. Needs triage
