### ISSUE TITLE
Handshake Failed

### ISSUE THREAD

**Issue by tvollscw** [nextcloud/talk-android#672] opened 2019-11-14 14:54 UTC
When entering in my server address, the app responds right away saying handshake failed.

I have my Nextcloud server set up with TLS 1.3 only.
I am **not** having issues with the Talk app on iOS.

From past issue tickets, I've seen others recommend changing settings in their server; but is this necessary if the iOS App works just fine?

**Comment by nickvergessen** [comment] 2019-11-14 15:06
Do you mind sharing a link to your instance and maybe a test account?
You can email it to `<my github name>@nextcloud.com`

**Comment by tvollscw** [comment] 2019-11-14 15:12
Unfortunately, It might take a little while. I JUST added a App to my nextcloud instance and for some reason, now I have an Internal Server Error that I need to look further into.

**Comment by tvollscw** [comment] 2019-11-14 17:56
Fixed it! For some reason, the files_reader app breaks my NC 17 install (500 error when loading GUI). Fixed it by disabling the app from the command line. 

I have sent you an email with the information needed for troubleshooting! Can you verify to me that you received the email?

**Comment by nickvergessen** [comment] 2019-11-18 15:40
I could reproduce the issue with your server. I guess some SSL config is not fully correct. Maybe you can check it again?

**Comment by tvollscw** [comment] 2019-11-18 15:49
Like I said, this issue does not happen on the iOS Talk App. Which makes me think, while I could modify my SSL config, It is probably something that should be fixed in the Android Talk App as well. Otherwise, I'm just plugging up a hole that could just have been an implemented fix.

**Comment by nickvergessen** [comment] 2019-11-18 15:53
Well maybe the iOS app actually need patching. I will check back with the developers after their vacation.

The problem I see is e.g. https://www.ssllabs.com/ssltest/ reporting "DNS CAA | No" which could be part of the problem.

**Comment by tvollscw** [comment] 2019-11-18 15:58
Strange. I am using a self-signed cert with Cloudflare as my HTTPS Proxy. If that gives any more background information.

**Comment by dadosch** [comment] 2019-11-24 21:57
Do you have android 7 @tvollscw ?

Because in android 7 there was a bug in some ssl implementation (see https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0)

This was fixed in the main Nextcloud app a while ago. So might not be a server issue, but a client issue (specific to android 7.0)

Apparently, this isn't fixed for nextcloud-talk. (Happens to me on Android 7, while works fine with Android 7.1.2)

**Comment by tvollscw** [comment] 2019-11-25 14:46
Currently running Android 9. I didn't have an issue previously when I was using TLSv1.2 on my server with Android 9, but now I'm exclusively using **only** TLSv1.3. That's the only noticeable change to my SSL settings to make this no longer work. However, my iPhone connects without an issue.

**Comment by dadosch** [comment] 2019-11-25 15:53
ok. i will open a separate issue for android 7.0 then.

**Comment by nickvergessen** [comment] 2019-11-25 19:45
@mario check out https://github.com/nextcloud/news-android/commit/4bad914c82527bdbf50ba01bf7e4c5bd9d1b7d24 which apparently solved this for the news app

**Closed** 2019-12-26 02:54 UTC

**Comment by dadosch** [comment] 2020-04-05 15:29
@mario is there any option this could be backported to v8.0.x?

**Comment by InQuize** [comment] 2022-11-06 19:52
Still having couple clients using Android 7, here are the steps I took to fix 'failed handshake' for them:
- Make sure that LetsEncrypt cert is issued using key generated with 256 bit ECDSA (384 won't work on Nougat because only `prime256v1` ECDH curve [is supported](https://stackoverflow.com/a/42047877/8862734)) or 4096/2048 bit RSA
- Make sure TLSv1.2 is allowed by server frontend, in my case HAProxy. Not sure if it will be necessary to disable TLSv1.3 on other servers like nginx or Apache, but in my case it worked with following ssl params:
`ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3 ecdhe prime256v1`
- Download (on Android device itself) and install `ISRG Root X1` self-signed LetsEncrypt CA using [.der](https://letsencrypt.org/certs/isrgrootx1.der) file obtained here:
https://letsencrypt.org/certificates/
Not sure if it is strictly necessary, but for some reason my LE cert chain fails right now on Nougat specifically, while on all other clients, so this was the fast and lazy fix.
