### ISSUE TITLE
Need an option to "ignore" calls in some rooms

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-android#212] opened 2018-06-26 13:22 UTC
…

**Comment by mario** [comment] 2018-06-26 13:46
I'd guess you'd want this mostly in group and public calls, right? Once I get the call type in a notification, those calls won't be as prominent as they are now - instead they'll get a simple notification + one-time sound.

**Comment by nickvergessen** [comment] 2018-06-26 13:50
Yeah well the internal room jan created earlier had 4 calls already :D

**Comment by mario** [comment] 2018-06-26 13:56
Get me call types :P

**Comment by jancborchardt** [comment] 2018-06-27 16:52
The calls just happened because of a bug that @schiessle encountered (in the Android Talk app) where tapping the conversation started a call instead of a chat.

So that should be fixed rather than adding the requested setting.

**Comment by jancborchardt** [comment] 2018-06-27 16:54
Also, this is a duplicate of #205

**Closed** 2018-06-27 16:55 UTC
