### ISSUE TITLE
Feature Request Screen Sharing

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/talk-android#2842] opened 2023-03-07 08:39 UTC
It would be nice if the screen of an IOS Device can be shared.
For example from an Ipad,
If external screens are connected the screen should be chooseable.

**Comment by mahibi** [comment] 2023-03-10 08:14
duplicate of https://github.com/nextcloud/talk-android/issues/1530

for iOS please have a look at https://github.com/nextcloud/talk-ios

**Closed by mahibi** 2023-03-10 08:14 UTC
Labels: enhancement, 0. Needs triage

**Comment by MrLoverLoverMMMM** [comment] 2023-11-21 10:42
I would really be happy if this feature would not be set to ice.
Goto Webinar, Goto Meeting, Teams,... many more already support screenshare.
I wanna use my phone for presentations in Samsung Dex and with this feature I could replace my presentation pc.
