### ISSUE TITLE
Display issue (ciuting a piece oit of it) in conversation view.

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/talk-android#1163] opened 2021-04-23 21:43 UTC
see attached screenshot.

Oneplus 8 pro, no special settings.
![Screenshot_20210423-234237](https://user-images.githubusercontent.com/10380051/115932702-b8a38400-a48d-11eb-8149-779f093387c0.jpg)

**Comment by mahibi** [comment] 2021-04-26 09:38
this is a duplicate of https://github.com/nextcloud/talk-android/issues/955
it was fixed by https://github.com/nextcloud/talk-android/pull/1057 and will be published with the next release

**Closed by mahibi** 2021-04-26 09:38 UTC
