### ISSUE TITLE
Push notification fallback

### ISSUE THREAD

**Issue by realquink** [nextcloud/talk-android#1744] opened 2021-12-16 16:53 UTC
Hi!

I would love a push notification fallback in the app for those of us who don't have Google play services installed. 

Thanks for reading!

**Comment by mahibi** [comment] 2021-12-20 14:08
that is an understandable wish, but it won't happen anytime soon. For workarounds you could have a look at that is an understandable wish, but it won't happen anytime soon. For workarounds you could have a look at https://github.com/nextcloud/talk-android/issues/257 

closing as duplicate of #257

**Closed by mahibi** 2021-12-20 14:08 UTC
Labels: enhancement, 0. Needs triage
