### ISSUE TITLE
Voice message not working

### ISSUE THREAD

**Issue by siriwliw98** [nextcloud/talk-android#3341] opened 2023-09-25 14:45 UTC
### Steps to reproduce

1. Click on the voice message playback button
2. The button spins without starting the playback of the voice message

### Expected behaviour

Start playing the voice message

### Actual behaviour

Hello, since the last update of Talk on Android (17.1.0), the playback of voice messages no longer works; it keeps buffering endlessly. I've tested the app on different phones: Samsung Note 9 and Samsung S8+, and the issue persists. Thank you for your assistance

### Device brand and model

Samsung note 9

### Android version

10

### Nextcloud Talk app version

17.1.0

### Nextcloud server version

25.0.12

### Talk version

15.0.8

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by mahibi** [comment] 2023-09-27 09:14
thanks for the report!
closing as duplicate of https://github.com/nextcloud/talk-android/issues/3325

**Closed by mahibi** 2023-09-27 09:14 UTC
Labels: bug, 0. Needs triage
