### ISSUE TITLE
[Feature request] Call signal when ringing

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#454] opened 2019-02-09 12:07 UTC
I suggest adding a call signal when connecting to another user. Similar to a telephone connection.

This is missing. During the call, it is not known whether you are connecting to another user and when you have answered or disconnected.

**Comment by mario** [comment] 2019-06-07 08:36
Duplicate of #254

**Closed by mario** 2019-06-07 08:36 UTC
