### ISSUE TITLE
Group conversation picture

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/talk-android#943] opened 2020-11-26 09:38 UTC
Add the ability to set a group conversation picture. 
This is the link to the main issue: https://github.com/nextcloud/spreed/issues/927
Let's keep the conversation there so we can make this as consistent as possible across platforms.

**Comment by tobiasKaminsky** [comment] 2020-11-26 10:57
Although FTE talk dev will start at 1.12, I suspect that this will not be ready until NC21 release.

**Comment by nickvergessen** [comment] 2023-05-02 10:20
Duplicate of https://github.com/nextcloud/talk-android/issues/2555

**Closed by nickvergessen** 2023-05-02 10:20 UTC
Labels: enhancement, feature: 📄 conversations
