### ISSUE TITLE
Android users can transmit but not receive video when using Talk app and HPB.

### ISSUE THREAD

**Issue by mobymolly** [nextcloud/talk-android#936] opened 2020-11-15 11:19 UTC
Version: Talk Android 8.0.10 app
Issue: Android participants can **transmit  but not receive video** when the Nextcloud instance uses an External Signaling Server (HPB).

_Android to Desktop - Case 1 (Video partially working)_
When an Android user is having a video call with a desktop user, the desktop user can see them (but **not** vice versa).
Interestingly, if the desktop user shares their screen, the Android user can see the screen. Audio works both ways.

_Android to Android - Case 2 (Video not working)_
When an Android user is having a video call with another Android user, they **cannot see each other's video, but the audio works both ways**. Each Android user only sees their own video preview in the corner of their screen. 

_Android (in Chrome) to Any - Case 3 (Working)_
When an Android user uses the Chrome mobile browser to join the call instead of using the Talk Android app, both **the video and audio function normally** as if they were using a desktop. 

The Talk Android app seems to be not picking up on the URI to the External Signaling Server that is configured in Nextcloud. Is this hard coded in the Talk Android app? If so, it should not be hard coded and it should adopt the configuration value that is set on the Nextcloud instance.

**Comment by tobiasKaminsky** [comment] 2020-11-16 06:27
> The Talk Android app seems to be not picking up on the URI to the External Signaling Server that is configured in Nextcloud.

@nickvergessen any idea on this?

**Comment by anarchotaoist** [comment] 2021-02-17 05:28
This affects me also.
I confirm most of the above but add:
* Android talk to Desktop Brave Browser - camera opens on both but will not show on device it streams to.
Android Talk to Android Duckduckgo + Ghostery browser - works, but camera from browser chooses the back camera and has no option to flip to front.

**Comment by mahibi** [comment] 2021-02-19 14:35
@mobymolly @anarchotaoist Problems like these are well known. I'll try to dive in the sourcecode to fix this. Maybe there are things wrong with the session management. I assume this will take some time but it's high priority

**Comment by jakobroehrl** [comment] 2021-05-03 10:03
similar problems: https://help.nextcloud.com/t/mobile-cant-joined-started-audio-when-using-spreed-hpb/101194

**Comment by nickvergessen** [comment] 2021-05-19 12:16
@mahibi  closable?

**Comment by jakobroehrl** [comment] 2021-06-09 12:42
This problem still extists.

**Comment by rwb99** [comment] 2022-02-09 19:15
Same issue https://github.com/nextcloud/spreed/issues/6891#issue-1128912426

**Comment by rwb99** [comment] 2022-02-09 19:21
![image](https://user-images.githubusercontent.com/63825594/153274065-dc037a85-cbc8-43b6-afd9-fe724deb1963.png)
red is phone wifi ip (same nat)
blue is mobile data ip

just got https://github.com/strukturag/nextcloud-spreed-signaling working

**Comment by kisjuhos** [comment] 2023-01-26 09:04
@rwb99 Could you share how you got it working, please? I have the same issue.

**Comment by jmlgo** [comment] 2023-04-27 16:00
This issue is still present

**Comment by Martinligabue** [comment] 2023-06-16 11:53
> @mahibi closable?

I think the issue should be open, it's still a bug to this day, even with latest nextcloud app and server

**Comment by human-blip** [comment] 2023-06-18 08:50
I'm seeing this issue too. In short: the android app does not see video stream but screen sharing works fine and browser to browser works fine too. Browser app sees video stream from android no problems.

Nextcloud server 26.0.2 with Talk 16.0.4
Spreed signaling server v1.1.2
Android nextcloud talk version v17.0.0

Very happy to provide further info if requested.

**Comment by ETLin** [comment] 2023-06-27 05:50
nextcloud 27.0.0 by Nextcloud AIO v6.1.1
It's happened again. my android phones worked fine before upgraded.

**Comment by mahibi** [comment] 2023-06-27 09:35
seems to happen with janus version 1.x (which is used in recent NExtcloud AIO versions)
so closing as duplicate of https://github.com/nextcloud/talk-android/issues/2704

**Closed by mahibi** 2023-06-27 09:35 UTC
Labels: bug, needs info, feature: ☎️ call
