### ISSUE TITLE
Long press menu looks not good

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#1454] opened 2021-07-12 05:32 UTC
On Oneplus 5T/7T it works great. This is from Huawei:
![image](https://user-images.githubusercontent.com/24530680/125235670-1d2eec00-e2e3-11eb-8b2c-b77a9f31765a.png)

@AndyScherzinger

**Comment by mahibi** [comment] 2021-07-12 07:45
duplicate of #1273

**Closed by mahibi** 2021-07-12 07:45 UTC
Labels: 0. Needs triage, bug
